Add Ability to Manage New & Existing Passwords
browserpass/browserpass-extension pull request #290
Opened 2022-04-10 09:28 UTC by patgmiller

This will extend functionality of the `browserpass-extension` to save, edit, and remove new and existing passwords for each of a user's configured password stores.

2022-04-10 09:29 UTC, patgmiller commented
Closes #61

2022-05-09 05:50 UTC, erayd requested changes
I'm liking the look of this - thank you very much for your work on it so far, and sorry about how long it's taken for me to review this properly! There's some really solid progress in this PR, and I am very much in favour of the overall direction you're taking it in.

I think that a "loading data" screen would be a good idea. If the crypto operation takes a while (e.g. via a slow yubikey), things look a bit weird while it's waiting.

The icons other than the back icon look good, but the back one needs fixing - the style doesn't match the other ones (it's thicker, and uses square corners).

Lots of tooltips on the edit screen are missing. Copy tooltips from the detail screen are missing.

There are many places that use non-descriptive variable names (e.g. `obj`).

2022-05-09 05:50 UTC, erayd commented on src/popup/interface.js
> +    // console.log("Interface(settings, logins):", settings, logins);
Remove debug code.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +function Login(settings, obj = {}) {
Descriptive variable name please, missing docblock.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +Login.prototype.getRawPassword = function() {
What is the purpose of this? See also the following, which extracts prefixed secrets.
 https://github.com/browserpass/browserpass-extension/blob/77f6d18f8ea92e68fc0c020cb4065283e45a78c2/src/background.js#L889-L963.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +        symbols = "`~!@#$%^&*()_-+=:;<>,.?/",
Some standard symbols are missing.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> + * Retreive store object. Can optionally return only sub path value.
Spelling error.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> + * @todo Can be inheirited perhaps? And extended/overloaded?
Can you expand on this comment please?

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +        check = Array => Array.every(Boolean)
Why is `check` assigned at all? It's only referenced once, and doesn't simplify anything. `results.every(Boolean)` should be sufficient.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +    // console.log("Login.prototype.isLogin(obj):", check(results), results, check, obj);
Remove debug comment.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +    // console.log("Login.prototype.isValid() results:", check(results), results, check, obj);
Remove debugging code.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +        const action = (this.contentSha == null) ? "add" : "save";
Perhaps use an 'isNew' property? Overloading `contentSha` is not obvious.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +Login.prototype.isLogin = function(obj) {
No docblock.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +Login.prototype.isPass = function(file) {
No docblock. Also, what is the purpose of this method?

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> + * Validation, ready to save
Incomplete docblock.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +Login.prototype.save = async function(obj) {
No docblock.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +Login.prototype.setPassword = function(password = "") {
No docblock.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +        console.warn(`Login password should be of type 'string', received '${typeof password}' instead.`);
Where is the value for `password` coming from, that it could be something other than a string?

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +        if (secret.search(/\n\r?/) > -1) {
This is platform-dependent. Why not use `[\r\n]+`?

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Login.js
> +                /^.*((?:(<?\r)\n)|(?:\n\r?))/,
What is the purpose of this?

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Settings.js
> +    // @TODO: perhaps this should be default settings
Perhaps it should 😉. What are you trying to achieve with it?

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Settings.js
> +function Settings() {
Missing docblock.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Settings.js
> +Settings.prototype.canDelete = function (obj) {
Missing docblock.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Settings.js
> +Settings.prototype.canSave = function (obj) {
Missing docblock.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Settings.js
> +Settings.prototype.get = async function() {
Missing docblock.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Settings.js
> +Settings.prototype.isSettings = function(obj) {
Missing docblock.

2022-05-09 05:50 UTC, erayd commented on src/popup/models/Settings.js
> +    return obj.hasOwnProperty("theme");
This is not a good way to check for a class instance. Any other object with a direct 'theme' property would pass.

2022-05-09 05:50 UTC, erayd commented on src/popup/popup.js
> +            settings = await settingsModel.get(),
I'm unsure what you are trying to achieve with this settings class, so will need to review it again later.

2022-05-09 05:50 UTC, erayd commented on src/popup/popup.js
> +        m.route(document.body, "/list", {
I like this.

2022-05-09 05:50 UTC, erayd commented on src/popup/popup.js
> +                // no in-progress notice
Why not?

2022-05-09 05:50 UTC, erayd commented on src/popup/popup.js
> +        // console.log({ action, login, params });
Remove debug code.

2022-05-10 15:49 UTC, patgmiller commented on src/helpers.js
> + * @since 3.X.Y
@erayd what version will this be when it is merged? i was thinking 3.8.0

2022-05-10 20:44 UTC, erayd commented on src/helpers.js
> + * @since 3.X.Y
Probably 3.8.0, yes. Feel free to leave this as-is until right before merge though, if you like 🙂. I commented to ensure it gets picked up, but it doesn't need to be addressed immediately.

2022-05-11 01:55 UTC, patgmiller commented on src/popup/popup.js
> +            settings = await settingsModel.get(),
@erayd I added the settings class following reasons. 

1. Reduce number of times to settings are requested. I don't think it make sense to retrieve the settings for every request; especially since most of the time they won't have any changes. 
2. After switching the Login to a model class and switching to multiple views a unified method of retrieving the settings made more sense, so I went with the same approach.   

The `settings` are loaded initially in `popup.js` and then can be shared with each different view as it was being done before in the original `interface`. With the difference that `mithril` creates a new view object for each request, so this initial object is "cached" in the view modules.

2022-05-11 02:40 UTC, patgmiller commented on src/background.js
> +                console.log(response);
Sure, however I created the one for `delete`  from the `save` block which was implemented by you. So I wasn't sure if I should leave it or not.

```
git blame src/background.js -L 740,741
a7932177 (Steve Gilberd 2020-09-12 21:26:56 +1200 740)                 console.log(response);
a7932177 (Steve Gilberd 2020-09-12 21:26:56 +1200 741)                 if (response.status != "ok") {
```

2022-05-11 02:42 UTC, patgmiller commented on src/background.js
> +                    throw new Error(JSON.stringify(response)); // TODO handle host error
Is that a note for me to handle the `TODO` or was that a note for you? Because that comment was originally added by you, so I'm not sure if there is a specific error you're wanting to handle.

2022-05-11 02:45 UTC, erayd commented on src/background.js
> +                console.log(response);
I'll double check that one then - thanks 🙂. It's entirely possible that I've accidentally left something there that shouldn't be.

2022-05-11 02:47 UTC, erayd commented on src/background.js
> +                    throw new Error(JSON.stringify(response)); // TODO handle host error
That was me seeing a TODO comment in an added line, and noting that it needs doing. If it isn't yours (e.g. if it was just moved from somewhere else), then don't worry about it for this PR.

2022-05-11 02:48 UTC, patgmiller commented on src/background.js
> +                console.log(response);
No problem, let me know either way. I don't have a reason for keeping it.

2022-05-11 02:55 UTC, patgmiller commented on src/popup/popup.js
> +                // no in-progress notice
I think my main reason for excluding a notice here was because the `handleError` replaces the dom elements and so if it fails the user would loose all of their changes or worse loose a completely new login credential.

I was thinking we needed to have a different notice mechanism perhaps? not exactly like a toast message but something that doesn't immediately remove the existing login details until it succeeds, what do you think? @erayd

2022-05-11 02:57 UTC, patgmiller commented on src/popup/popup.js
> +        m.route(document.body, "/list", {
Me too! 😃

2022-05-11 02:59 UTC, erayd commented on src/popup/popup.js
> +                // no in-progress notice
That makes sense - I agree. A different mechanism would be fine. I do think it's important that we have *some kind* of "we're busy doing a thing" feedback for the user though, especially noting that users with hardware tokens are a niche that Browserpass specifically targets, and some of those tokens are **slow**.

2022-05-11 03:01 UTC, erayd commented on src/popup/popup.js
> +                // no in-progress notice
On `handleError` specifically, would you be open to refactoring that as well? Now that DOM-replacement is no longer the default action, it would be nice to have it behave in a way that doesn't just automatically nuke things we don't want nuked.

2022-05-12 03:45 UTC, patgmiller commented on src/popup/popup.js
> +                // no in-progress notice
Sure I can look at refactoring it. @erayd do you know of any specific hardware tokens that are slow; I mean that I could use for reference? Or even just some commonly used ones to target would be good know.

2022-05-12 03:47 UTC, erayd commented on src/popup/popup.js
> +                // no in-progress notice
> do you know of any specific hardware tokens that are slow...

YubiKey Neo is an example of such a token. It's not horrifically slow, but it's slow enough to notice.

2022-05-12 05:24 UTC, patgmiller commented on src/popup/popup.js
> +                // no in-progress notice
Okay thanks! I'll take a look at that.

2022-05-12 05:35 UTC, patgmiller commented on src/helpers.js
> + * @param object origin     Instance of BrowserpassURL (optional, default: new BrowserpassURL(settings.origin))
On line `100` if `origin` is undefined it is set to an `new BrowserpassURL()` before any processing on `origin` is handled. I felt it was a little long to put in the function definition, is there something else you would prefer?

```js
origin = origin == undefined ? new BrowserpassURL(settings.origin) : origin;
```

2022-05-12 05:41 UTC, patgmiller commented on src/popup/detailsInterface.js
> +                                let updateProgress = (vnode) => {
I'll admit I didn't do much with the progress bar beyond converting this view to work with the mithril routing view approach. So I'll have to take look at it. Off the top of my head I'd guess it has to do with not properly show/hide -ing elements either it's default state, or during a transition.

2022-05-12 06:03 UTC, patgmiller commented on src/popup/models/Login.js
> +Login.prototype.getRawPassword = function() {
So the main purpose of `Login.prototype.getRawPassword` is share some common functionality in getting the `password` or `secret` of the login in the `add / edit` view. 

The short answer is really in approaching the question, "How do I keep the secret input and raw details in sync?" Because with add / edit functionality one can edit the `password` / `secret` in two places. I just went with update the other location with each new change.

add / edit view has these update on input
https://github.com/browserpass/browserpass-extension/blob/ddbc54595f20dd02fd5587ddab6cb44475313de4/src/popup/addEditInterface.js#L61-L67

and the `Login` will update when the password is set 

https://github.com/browserpass/browserpass-extension/blob/ddbc54595f20dd02fd5587ddab6cb44475313de4/src/popup/models/Login.js#L241-L242

2022-05-12 06:09 UTC, patgmiller commented on src/popup/models/Login.js
> +        symbols = "`~!@#$%^&*()_-+=:;<>,.?/",
You're right, I didn't put everything in there, is there a specific set you'd like me to use? At the time I think I "grabbed a handful" and threw them in there.

2022-05-12 06:15 UTC, patgmiller commented on src/popup/models/Login.js
> +        symbols = "`~!@#$%^&*()_-+=:;<>,.?/",
If we're being 100% accurate I think we would be as close to the `man pass` details on `pass generate` doc; however at the time I didn't stop to figure out how we should do that exactly.

```doc
generate [ --no-symbols, -n ] [ --clip, -c ] [ --in-place, -i | --force, -f ] pass-name [pass-length]
      Generate a new password using /dev/urandom of length pass-length (or PASSWORD_STORE_GENERATED_LENGTH if unspecified) and insert into pass-name. If --no-symbols or -n is specified, do not use any  non-alphanumeric
      characters  in  the  generated  password.  The  character  sets used in generating passwords can be changed with the PASSWORD_STORE_CHARACTER_SET and PASSWORD_STORE_CHARACTER_SET_NO_SYMBOLS environment variables,
      described below.  If --clip or -c is specified, do not print the password but instead  copy  it  to  the  clipboard  using  xclip(1)  or  wl-clipboard(1)  and  then  restore  the  clipboard  after  45  (or  PASS‐
      WORD_STORE_CLIP_TIME) seconds. If --qrcode or -q is specified, do not print the password but instead display a QR code using qrencode(1) either to the terminal or graphically if supported. Prompt before overwrit‐
      ing an existing password, unless --force or -f is specified. If --in-place or -i is specified, do not interactively prompt, and only replace the first line of the password file with the  new  generated  password,
      keeping the remainder of the file intact.
```

2022-05-12 06:29 UTC, patgmiller commented on src/popup/models/Login.js
> +        symbols = "`~!@#$%^&*()_-+=:;<>,.?/",
Actually, `pass` just uses these, I can just copy those for now?

```shell
CHARACTER_SET="${PASSWORD_STORE_CHARACTER_SET:-[:punct:][:alnum:]}"
CHARACTER_SET_NO_SYMBOLS="${PASSWORD_STORE_CHARACTER_SET_NO_SYMBOLS:-[:alnum:]}"
```

2022-05-12 06:39 UTC, patgmiller commented on src/popup/models/Login.js
> +        symbols = "`~!@#$%^&*()_-+=:;<>,.?/",
You just wanted all of these right?
```text
abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890
 ! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~.
```

2022-05-14 09:36 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                        m("div.btn.back", {
Yep you're right. I know this worked before I submitted the PR because I went back and reviewed my last video demo of it. Regardless, it's stopped working so I'll get it fixed.

2022-05-14 09:41 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
@erayd i'm not sure I follow. Do you mean we put `example.gpg` as a `placeholder` and then auto append `.gpg` to the text? So we'd drop the `.gpg` from the end of the line, right?

2022-05-14 09:49 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
@erayd actually I completely left off the highlights in edit mode because I didn't even think about including them. However, the "highlights" are handled by wrapping the letters with span elements, wouldn't that change the resulting secret value? Also, the add edit lines are form fields so I think that might complicate things, unless perhaps I'm missing something?

2022-05-15 00:45 UTC, patgmiller commented on src/popup/models/Settings.js
> +    return obj.hasOwnProperty("theme");
@erayd well I can fix it if you like. However, I did that specifically because I didn't want to require that we refactor the `src/helpers.js` and `src/interface.js` to require that their `settings` objects adhere to the `Settings.prototype` so you could describe this as a loosely typed Settings class. 

However, it will probably be more stable and consistent to treat it the same everywhere, so I'll correct it.

2022-05-24 03:10 UTC, patgmiller commented on src/helpers.js
> +        index: (index = isFinite(index) && index > -1 ? parseInt(index) : 0),
I guess b/c I come from the school of never trust anything, so validate and sanitize. For example 

```javascript
Math.max(0, undefined)
> NaN
```

and the ternary will give me a boolean so I just use the default.  
```javascript
undefined > -1 
> false
```

I'm happy to remove the `isFinite` since checking for a possible Infinite is unnecessary.

2022-05-24 03:11 UTC, patgmiller commented on src/helpers.js
> + * @param number index      An array index for login, if building an array of logins (optional, default: 0)
Added default of `0`

2022-05-24 03:11 UTC, patgmiller commented on src/helpers.js
> + * @param object origin     Instance of BrowserpassURL (optional, default: new BrowserpassURL(settings.origin))
Added a default `undefined` and then only use `origin` is it is a prototype of `BrowserpassURL`

2022-05-24 03:14 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                        m("div.btn.back", {
I can reliably duplicate this, but it doesn't always happen. It depends on what the path for the `login` is. But as of yet I don't know the exact cause of the issue.

2022-05-30 22:55 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
@erayd how badly do you want the "highlights" in the `edit` view? My personal opinion is they should not be used when editing the pass secret. I feel that way b/c the symbols include `</>` characters and those will likely mess with any effort to "sanitize" the users secret before saving. 

It think it is doable, but not without taking great care to ensure we're not corrupting the users secrets.

2022-05-30 23:04 UTC, erayd commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
I'm keen to have it unless there are notable reasons to avoid it. However, if you're finding it problematic, we can omit it from this PR and add the capability later.

Can you expand a bit on why you think that would be a problem? It shouldn't matter what symbols are in the secret; browser DOMs have no issue with handling special characters.

Note that the *display* of the secret (with highlighting) does not need to be the same element as the input. It can be a synchronised overlay (or underlay).

2022-05-30 23:28 UTC, erayd commented on src/popup/models/Login.js
> +        symbols = "`~!@#$%^&*()_-+=:;<>,.?/",
That looks fine. Basically I'm thinking we should have all of ASCII printable, unless there are good reasons to omit particular symbols.

Unfortunately javascript regex doesn't support `[:punct:]`, however the symbol string you've posted should suffice.

2022-05-30 23:32 UTC, erayd commented on src/helpers.js
> + * @param object origin     Instance of BrowserpassURL (optional, default: new BrowserpassURL(settings.origin))
That sounds reasonable. Having the default set as undefined (rather than omitted) makes it explicit that it's the intended behaviour.

2022-05-30 23:35 UTC, erayd commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
I'm just talking about the positioning of the `.gpg` at the end. I don't think we need to be appending it within the actual input value, but it does need to look like it's part of the string, vs all the way over on the right side of the screen.

2022-05-30 23:37 UTC, erayd commented on src/popup/models/Login.js
> +Login.prototype.getRawPassword = function() {
Makes sense. Note the case where the secret may be prefixed.

2022-05-31 03:22 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
If we're only talking about adjusting the `.gpg` then I think I understand now, I'll work on adjusting as you described.

2022-05-31 03:31 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
My only concern was in maintaining the accuracy of whatever the user has for their password / secret value. Using a second element to display / render the highlighting would be very simple solution to that. So @erayd my only question to clarify on that would be do we then show both the editable input, the highlight, and the full raw details down below? Or possibly do we make use of the "synchronizing" that I already have it doing and have the `Secret` form field be the highlighted portion and let the details be the editable portion? Or something else entirely? I'm option to suggestions on it.

2022-05-31 03:53 UTC, patgmiller commented on src/popup/models/Login.js
> +Login.prototype.getRawPassword = function() {
@erayd Okay. I think you mean the specific case for `otp`? But that brings up a question for me. Should we handle `otpauth://` secrets differently than others? Perhaps disable `generate` functionality or something? As it is now, the user would be able edit those, on purpose or accidental, but we could do something to help avoid it.

2022-05-31 04:03 UTC, patgmiller commented on src/popup/models/Login.js
> +Login.prototype.isPass = function(file) {
I think I added it early on with the idea I might need to check the login path, but it currently it is completely unused so I'm removing it.

2022-05-31 04:07 UTC, erayd commented on src/popup/models/Login.js
> +Login.prototype.getRawPassword = function() {
No, I wasn't talking about OTP specifically - rather, I was referring to the case when the first line of the file may be prefixed (e.g. with `password`, `secret` etc). That is one of the situations that the current parsing code handles, but yours doesn't seem to account for yet. It's in violation of convention (which is that the first line should always be naked), but it's come up enough that I think it's important for us to handle it anyway.

Your suggestion about disabling the generate-password feature when the first line is an OTP seed is a very good one. I agree strongly.

2022-05-31 04:08 UTC, patgmiller commented on src/popup/models/Login.js
> +        console.warn(`Login password should be of type 'string', received '${typeof password}' instead.`);
Honestly, with my background mostly in server side I've always considered client side code to be rather insecure, or rather to always mistrust it. If you think it's unnecessary I can remove it.

2022-05-31 04:13 UTC, erayd commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
For the sake of implementation simplicity, I think the best course is probably to have the 'secret' section of the UI be display-only, and do the actual editing in the part where the rest of the file content is displayed. And then if users complain and want to be able to edit it in both places, implement an input overlay at that point. I'd not considered this until you mentioned it above, but I think it makes the most sense.

If you feel like spending the time messing with it anyway, and want to do an overlay now, that would be useful. But I think it's a nice-to-have.

@maximbaz what are your thoughts on this one?

2022-05-31 04:16 UTC, patgmiller commented on src/popup/models/Settings.js
> +    // @TODO: perhaps this should be default settings
@erayd I don't quite understand your question. My only reason for having the `@TODO` there was to revisit on if I would include setting defaults there. However, that would duplicate where the defaults are managed and probably not a good idea. I was thinking I would just remove the comment and leave this as it is.

2022-05-31 04:16 UTC, erayd commented on src/popup/models/Login.js
> +        console.warn(`Login password should be of type 'string', received '${typeof password}' instead.`);
I think it's unnecessary in this case (although I do agree with your point more generally), but am not opposed to it remaining. If you'd like to keep it, it can stay 🙂. I was more wanting to understand why you'd done this in the first place.

2022-05-31 04:20 UTC, erayd commented on src/popup/models/Settings.js
> +    // @TODO: perhaps this should be default settings
It looked like you weren't sure about it, so I commented with the goal of understanding what you weren't sure about.

Your reasoning in the above comment (avoiding managing defaults in multiple places) makes sense, and I agree with you.

2022-05-31 04:28 UTC, patgmiller commented on src/popup/models/Login.js
> +Login.prototype.getRawPassword = function() {
Ah, so some have actually put `password:` in their password for whatever reason. Got it, okay I'll include it.

2022-05-31 04:30 UTC, erayd commented on src/popup/models/Login.js
> +Login.prototype.getRawPassword = function() {
Yes, exactly!

2022-05-31 04:31 UTC, patgmiller commented on src/popup/models/Login.js
> +        console.warn(`Login password should be of type 'string', received '${typeof password}' instead.`);
I think it was another early case in which I was being overly cautious. I don't think it provides much value here, so I'll just remove it.

2022-06-02 01:40 UTC, patgmiller commented on src/popup/models/Login.js
> +        const action = (this.contentSha == null) ? "add" : "save";
@erayd are you okay if the `isNew` uses a `contentSha` 😄

2022-06-02 01:43 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                                        var remove = confirm(
Sure I'll work on it.

2022-06-02 01:45 UTC, erayd commented on src/popup/models/Login.js
> +        const action = (this.contentSha == null) ? "add" : "save";
Provided you correctly handle the case of an empty entry (i.e. a file that, once decrypted, yields no content), yes.

2022-06-04 20:26 UTC, patgmiller commented on src/background.js
> +        case "delete":
@maximbaz @erayd regarding symlink deletion, what do you think about doing something like one of the following options?

1. Never delete a symlink. Here, I would respond with an error from the native app when a delete is attempted on a symlink. Also, I would consider including a property or meta data when listing files if one is a symlink and adjust the client side extension to disable the ability to at least delete a symlink.
2. Allow deleting, but only if the target exists within the browserpass tree. 

Let me know your thoughts, I'm fine also submitting changes host app repo based on the `implement-tree-save-delete` branch if you want.

2022-06-04 23:02 UTC, maximbaz commented on src/background.js
> +        case "delete":
First, apologies for still being very slow to respond, I do intend to review this properly, but do keep going! 🙂 

Things on my mind regarding the symlinks in general:

1. We need to gracefully handle broken symlinks in any case (we may be doing that already).
2. Need to make sure editing symlinks edits the target entry.
3. What about _creating_ symlinks (creating amazon.co.uk -> amazon.com) - even if UI for this is not part of this PR, do we want this capability in the native host?
    1. What about editing symlink destination? Although not to over-complicate this, I'd probably just delete the symlink and create it, if I had such capabilities?
4. I'm a bit hesitant when it comes to adding a lot of magic, such as removing all dangling symlinks when an entry is removed - right now Denmark is transitioning to a new domain for gov ID login (which lots of sites use, so I have lots of symlinks), if I delete the old domain, I (...maybe?) may actually want to have all those broken symlinks preserved, to then explore and decide if I want to re-link them to the new domain or not. 
5. We should try to test symlinks with relative and absolute paths
6. We should remember to make sure Windows symlinks are supported too, both relative and absolute

My current thoughts regarding what to do are:
- We can differentiate a real entry from a symlink
  - Need this capability in the native host
  - UI-wise, maybe a tiny icon just like "last used", which on hover can show the location of the symlink, exactly how it is in file system?
- Remove of symlink should just remove the symlink, as if you perform `rm` command in terminal
- Remove of the entry should not delete all symlinks, again as if you run `rm` in terminal
- Edit should edit the target file, just like `pass edit <symlink>` edits the real entry
- It would be cool to be able to create a symlink directly from extension, but totally fine to leave it for later
- Editing symlink destination is thus simply two commands, remove of symlink followed by creation of symlink

What do you guys think?

2022-06-04 23:35 UTC, maximbaz commented
Nice work, huge thanks, it's very not trivial task you picked, so we and the rest of the community are very grateful!

Some initial comments from me just testing it from a user perspective:

1. Add credentials -> focus "Secret" -> type "ab" -> press Backspace twice ==> it cannot remove "a", one char incorrectly remains
2. Generate secret button always overwrites the first line, does not account for `password:` line or the likes (applies for both "Add credentials" and "Edit", try to edit the following existing entry and use "Generate button" to update the password):

```
user: superman
password: batman
recovery phrase: kryptonite
phone: 1234567
```

The same applies to what content the "Secret" field displays while editing the contents of textarea, if I type the above from scratch, as soon as I type `password:` in the textarea, the "Secret" value should update from `user: superman` to empty.

A few other "big" ones for me:

3. I don't like the fact that our fields and textareas have exactly the same colors when they are readonly (after pressing `>`) and when they are writeable (when going into "Edit" mode), as a user I can't easily tell if a field is mutable or not without clicking into it - I feel like we need a bit different colors for the "Edit" mode, to make it clearer perhaps?
4. Tiny "Save" icon button hidden in the corner and a huge orange "Delete" button right underneath the form make a wrong impression of what is the primary form action, some people for sure will hit the wrong one 🙂 I'd just swap them, have the "Save" big and bright in the bottom, and keep "remove" as a trash icon in the top where it doesn't attract much attention. Other ideas are also welcome 🙂 
3. My Yubikey is setup to require a touch to decrypt an entry, I quite don't like seeing the empty form during that period after pressing `>`, Browserpass feels a bit broken, can we perhaps have some "Loading..." instead of the unfilled form in this case? This applies to all cases when `gpg` operation is slow, yubikey does not necessarily have to be involved 🙂 

![image](https://user-images.githubusercontent.com/1177900/172028797-5a8e3aa9-424b-4b74-ab09-fbb472ca0678.png)

And some which are maybe considered minor:

5. We are decrypting the entry twice (once when we click `>` button, and once more when we click "Edit" button), which requires touching Yubikey twice, and which I believe in earlier erayd's prototype wasn't the case - is it possible to avoid re-decrypting the entry? Or maybe you have some good arguments against this idea?
    - I can also see that when I hit "Delete" button, after confirmation there is yet another attempt to decrypt an entry, which shouldn't be the case?
 
7. It was counter-intuitive for me to see "Secret" and "Login" fields above textarea when I pressed `>`, but after clicking "Edit" the "Login" disappears, and only "Secret" field remains - what was the rationale behind that? 🙂 
8. "Length" number input has buttons `^` and `v` and I can go into negative numbers using them, the value should be bound with `1` as minimum.

2022-06-05 22:31 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                        m("div.btn.back", {
Note: This also happens after using the search form to filter the results.

2022-06-25 23:56 UTC, patgmiller commented on src/background.js
> +        case "delete":
@maximbaz @erayd I am fine with everything after, 

> My current thoughts regarding what to do are:

and the tiny icon could just be your typical link icon like what is used to create URL links in WISWYG editors. So long has creating symlink and editing symlink target is for a separate feature ticket.

It looks like currently editing any symlink is just handled by the OS and the behavior is that it just changes the target contents.

On this, 

>1. We need to gracefully handle broken symlinks in any case (we may be doing that already).

It would depend on the type of symlink, a normal (or hard) symlink would still work just fine, as I mentioned already. However a broken `symbolic` link just fails decryption, and shows nothing on the details. It should probably raise an error. Honestly I have to wonder if symbolic links are even used b/c they just don't work well at all in `pass`. They `always` return in `pass [find, search]` results. For both the autocomplete and `pass show` it just behaves as if the broken symbolic link doesn't exist. 

```shell
# example showing always in search results regardless
devpass find foo                                                                                       
Search Terms: foo
├── browserpass
│   └── testing
│       ├── foo
│       └── symbolic-link -> regular-file
└── food
    └── dominos.com

# fails decryption as if the symbolic does not exists, b/c well ... the target doesn't exist. 
devpass browserpass/testing/symbolic-link
Error: browserpass/testing/symbolic-link is not in the password store.
```

2022-06-26 00:07 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
It has been a while since I've responded with an update. Last time I worked on any of it I spent most of my time working on including the highlight in the edit page and refactoring that view so all edits are done in just the `textarea`.

However allowing the `secret prefix` has proven a little tricky / problematic while editing. So I needed to take a break, but I have most of it worked out and so I thought you'd like me pass that along.

2022-06-26 00:25 UTC, patgmiller commented
@maximbaz regarding `#4` from [your last comment block](https://github.com/browserpass/browserpass-extension/pull/290#issuecomment-1146703020), I don't completely disagree; but I think there is a problem with the part about putting the `Delete` action / icon in the top right. That is, will be, the exact same location of the `Edit` button on the previous `Details` page and some double click happy users may accidentally hit it. I think you make a good point. Perhaps the Save should be a bigger button bottom left, and put the Delete bottom right (or vice versa) so they're more obvious but not next to each other? Kind of like on other sites where the save and delete type actions are at the bottom but the destructive actions are clearly separated from the save actions? How does that sound?
![edit-buttons](https://user-images.githubusercontent.com/3914379/175794527-f2640fca-ea82-4886-a542-2a1c6deee03b.jpg)

2022-06-26 10:56 UTC, maximbaz commented
I agree with the argument, lets try and see how it looks! 🙂

2022-06-27 03:53 UTC, patgmiller commented
Hey @maximbaz, just responding to your overview.

> 1. Add credentials -> focus "Secret" -> type "ab" -> press Backspace twice ==> it cannot remove "a", one char incorrectly remains

My bad, I assumed we wouldn't have an empty raw text value, it's an easy fix. One question though, shouldn't we require the raw text details to be some non-empty value when validating it is okay to save? I am referring to the `Login.prototype.isValid(loginObj)`  method which I use to check if required items are present before saving. In short basic form validation for require inputs and formats etc.

> 2. Generate secret button always overwrites the first line, does not account for `password:` line or the likes (applies for both "Add credentials" and "Edit", try to edit the following existing entry and use "Generate button" to update the password):
> 
> ```
> user: superman
> password: batman
> recovery phrase: kryptonite
> phone: 1234567
> ```
> 
> The same applies to what content the "Secret" field displays while editing the contents of textarea, if I type the above from scratch, as soon as I type `password:` in the textarea, the "Secret" value should update from `user: superman` to empty.

I hope I'm not miss-understanding this one, but in addition to having an optional prefix (I've recently addressed this and pushed changes), the secret/password can also be found on any line? Isn't that a large move away from `pass` since it only grabs the first line from the text for clipboard? Or is this similar to the secret prefix where it's being done anyway so we'll be nice and support it?

> 3. I don't like the fact that our fields and textareas have exactly the same colors when they are readonly (after pressing `>`) and when they are writeable (when going into "Edit" mode), as a user I can't easily tell if a field is mutable or not without clicking into it - I feel like we need a bit different colors for the "Edit" mode, to make it clearer perhaps?

Sure, that would be good to do.

> 4. Tiny "Save" icon button hidden in the corner and a huge orange "Delete" button right underneath the form make a wrong impression of what is the primary form action, some people for sure will hit the wrong one slightly_smiling_face I'd just swap them, have the "Save" big and bright in the bottom, and keep "remove" as a trash icon in the top where it doesn't attract much attention. Other ideas are also welcome slightly_smiling_face

We already talked about this one. 

> 5. My Yubikey is setup to require a touch to decrypt an entry, I quite don't like seeing the empty form during that period after pressing `>`, Browserpass feels a bit broken, can we perhaps have some "Loading..." instead of the unfilled form in this case? This applies to all cases when `gpg` operation is slow, yubikey does not necessarily have to be involved slightly_smiling_face

Yep it's on the list to address, @erayd also mentioned needing some kind of "loading, ..." instead of an empty form.

> 5. We are decrypting the entry twice (once when we click `>` button, and once more when we click "Edit" button), which requires touching Yubikey twice, and which I believe in earlier erayd's prototype wasn't the case - is it possible to avoid re-decrypting the entry? Or maybe you have some good arguments against this idea?
>    
>    * I can also see that when I hit "Delete" button, after confirmation there is yet another attempt to decrypt an entry, which shouldn't be the case?

So my first thought about the multiple decryption requests, we probably should try to handle it as close to the PGP client settings. However, that may be a bigger task. One possible step in that direction is to have an option to cache decrypted responses for say 30 sec, 1 min, or 2 min. Maybe the cache approach is an opt in setting and the timeout can be selected? @maximbaz @erayd I'd like your general input on that before I look at any specifics.

> 6. It was counter-intuitive for me to see "Secret" and "Login" fields above textarea when I pressed `>`, but after clicking "Edit" the "Login" disappears, and only "Secret" field remains - what was the rationale behind that? slightly_smiling_face

Probably had more to do with my lack of familiarity of how important the prefixes are in browserpass. I just figured the raw text area was all editable to the users heart's content and only kept the Secret field b/c the rest of the inputs were focused on the password only; eg. generate, symbols, and length.

> 7. "Length" number input has buttons `^` and `v` and I can go into negative numbers using them, the value should be bound with `1` as minimum.

No problem I will fix it.

2022-06-27 11:27 UTC, maximbaz commented
> So my first thought about the multiple decryption requests, we probably should try to handle it as close to the PGP agent settings (conf). However, that may be a bigger task. One possible step in that direction is to have an option to cache decrypted responses for say 30 sec, 1 min, or 2 min. Maybe the cache approach is an opt in setting and the timeout can be selected? @maximbaz @erayd I'd like your general input on that before I look at any specifics.

Let's not do any configurable caching - my idea is much simpler than that 🙂  When I click `>` button to see details of the password entry, the data is _already_ visible to me in the popup, when I then click "edit", as a user I expect no new decryption operation, as all the things are already decrypted (again, I see them in plain text! 😁 ), just the form should become editable.

2022-06-27 18:01 UTC, maximbaz commented
I have indeed configured touch requirement for every decryption operation. OK I probably need to look at the code before giving any further comments, so far I was commenting purely from a user perspective, where as a user I naturally assume that the entry is already decrypted in the context of the open popup. If it is too difficult to implement, I'd be fine with re-decryption, let's focus on the other items in the TODO list.

2022-07-01 01:12 UTC, patgmiller commented
> I have indeed configured touch requirement for every decryption operation. OK I probably need to look at the code before giving any further comments, so far I was commenting purely from a user perspective, where as a user I naturally assume that the entry is already decrypted in the context of the open popup. If it is too difficult to implement, I'd be fine with re-decryption, let's focus on the other items in the TODO list.

It's not too difficult, it just seems like when I think I'm getting close to completing the todo list gets a little longer and I can't help but think that we could've broken it up into smaller chunks.

2022-07-01 02:03 UTC, erayd commented
> It's not too difficult, it just seems like when I think I'm getting close to completing the todo list gets a little longer and I can't help but think that we could've broken it up into smaller chunks.

It seems quite odd to me that we can't simply grab the `textContent`, rather than decrypting it again. But fi you'd prefer to leave it for now, and deal with it after this PR is merged, I'm OK with that too. If we go down that route though, we should open an issue to track it, because I don't want to leave it that way.

2022-07-01 02:10 UTC, erayd commented
> One question though, shouldn't we require the raw text details to be some non-empty value when validating it is okay to save?

Yes. If. it's empty, something is probably wrong, and we therefore shouldn't be saving it. If the user wanted to nuke the entry, they should probably be deleting it rather than saving an empty entry.

> I hope I'm not miss-understanding this one, but in addition to having an optional prefix (I've recently addressed this and pushed changes), the secret/password can also be found on any line?

Yes. The prefix clearly identified what it is, therefore we should treat it as the user intended. We already parse it that way now.

> Isn't that a large move away from `pass` since it only grabs the first line from the text for clipboard? Or is this similar to the secret prefix where it's being done anyway so we'll be nice and support it?

The latter. Users do it, and supporting it doesn't violate any expectations or add any UX complexity for the user, so we support it.

> So my first thought about the multiple decryption requests, we probably should try to handle it as close to the PGP agent settings (conf). However, that may be a bigger task. One possible step in that direction is to have an option to cache decrypted responses for say 30 sec, 1 min, or 2 min. Maybe the cache approach is an opt in setting and the timeout can be selected? @maximbaz @erayd I'd like your general input on that before I look at any specifics.

I really don't want us caching anything confidential that we don't absolutely have to cache, but I am OK with reusing already-decrypted content that we are currently displaying.

> Probably had more to do with my lack of familiarity of how important the prefixes are in browserpass. I just figured the raw text area was all editable to the users heart's content and only kept the Secret field b/c the rest of the inputs were focused on the password only; eg. generate, symbols, and length.

2022-07-05 14:49 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                        m("div.btn.back", {
Resolved with [f6f2e2a](https://github.com/browserpass/browserpass-extension/pull/290/commits/f6f2e2a6dd05dbb76617367a028547b083c1502c)

2022-07-09 16:51 UTC, patgmiller commented
> It was counter-intuitive for me to see "Secret" and "Login" fields above textarea when I pressed >, but after clicking "Edit" the "Login" disappears, and only "Secret" field remains - what was the rationale behind that? 

@maximbaz my rational behind not including the `login` field on the `addEdit` view was I following your original [suggested design](https://github.com/browserpass/browserpass-extension/issues/61#issuecomment-650750349).
![Screenshot_2022-07-09_10-48-07](https://user-images.githubusercontent.com/3914379/178115270-dd580e0e-348f-4912-8a76-9a6a6da87e04.png)

Also, since we doing all of the editing in the text area, i don't think it makes sense to allow editing in another field.

2022-07-09 18:04 UTC, maximbaz commented
Do not feel obliged to follow that original design if it limits your current improvement ideas 🙂 

I don't think I feel strongly about it, more like a confusion that the form suddenly changed... The same is true for password, we are allowing editing it in two locations...

2022-07-11 02:30 UTC, patgmiller commented
@maximbaz @erayd I have made `a lot` of changes / improvements to the extension and addressed most of your feedback, but not all yet. Please reference [my current todo's ](https://github.com/browserpass/browserpass-extension/issues/61#issuecomment-1166778554) list before providing any additional feedback. But if you wouldn't mind reviewing my latest updated changes I would appreciate it. Thank you.

2022-07-22 04:14 UTC, erayd commented
@patgmiller Thanks - will take a look at it. Still extremely busy, so it won't happen immediately, but I'll try to find some time for it in the next week or two.

2022-07-22 04:24 UTC, patgmiller commented on src/background.js
> +        case "delete":
@maximbaz @erayd  based on the [request/list.go line 39](https://github.com/browserpass/browserpass-native/blob/master/request/list.go#L39) the native host app is already following symlinks and every edit to link I've tested handles editing the target. Everything looks as it's already being handled as Maxim described minus the extra link icon. At this point I rather let be as is.

2022-07-22 04:26 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                                "select",
@erayd are you saying you think each select option should be styled to it's store colors

2022-07-22 04:30 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=checkbox]", {
@erayd what do you mean? the `generate` button isn't an active on/off button (like a toggle), it's a single click event button. I don't think what you're saying applies. 

I have adjusted the styles for it.

2022-07-22 04:34 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=number]", {
@maximbaz also commented on the length, which I've put a floor on at `1`.

2022-07-27 03:42 UTC, patgmiller commented
@erayd @maximbaz I've also replaced the deprecated `confirm` with a `<dialog>` element / component.

![Screenshot_2022-07-26_21-38-59](https://user-images.githubusercontent.com/3914379/181155948-1c1e560f-6e56-4956-b88f-b40d032abbc4.png)
![Screenshot_2022-07-26_21-38-03](https://user-images.githubusercontent.com/3914379/181155949-76e016eb-23b7-4b63-8bca-590bcfa692bb.png)

2022-08-01 02:25 UTC, patgmiller commented on src/background.js
> +    // host capabilities
Set, at minimum host application version will be `v3.1.0`.

2022-08-01 02:36 UTC, patgmiller commented
@maximbaz @erayd be advised I've set the host capabilities version in my branches. 

browserpass-extension (this pr)
```js
# src/background.js
    settings.version = response.version;
    const EDIT_VERSION = 3 * 1000000 + 1 * 1000 + 0;

    // host capabilities
    settings.caps.save = settings.version >= EDIT_VERSION;
    settings.caps.delete = settings.version >= EDIT_VERSION;
    settings.caps.tree = settings.version >= EDIT_VERSION;
```

https://github.com/patgmiller/browserpass-native/tree/implement-tree-save-delete
```go
# version/version.go
const major = 3
const minor = 1
const patch = 0

// Code version as integer
const Code = major*1000000 + minor*1000 + patch
```

2022-08-10 03:01 UTC, patgmiller commented
@maximbaz @erayd While reviewing part of the native host application I realized the `tree` request was intended to list directories for a password store. I've threw together a working rough draft of showing directories one level at a time. The tree and search results are like 95% done. I just need to make the UI nicer and include tab index and click events to append the selected director to the file path. See attached. 

[tree-search-dropdown.webm](https://user-images.githubusercontent.com/3914379/183800921-c6063626-40f7-41fa-9962-b6e3c8672867.webm)

2022-08-12 15:37 UTC, patgmiller commented
@erayd it's been three weeks, have you had a chance to review the changes?

2022-08-12 21:26 UTC, erayd commented
@patgmiller I'm midway through.

2022-08-12 21:33 UTC, patgmiller commented
Awesome! I'm super excited about it 😄

2022-08-14 01:33 UTC, patgmiller reviewed
Mark my review as finished.

2022-08-28 19:00 UTC, patgmiller commented
@erayd @maximbaz I know Steve is doing his review right now, but while I was using it I felt like the tree browsing + filtering could use a little more help. So I added `Home`, `End`, `PageUp` and `PageDown` handlers for when the directory tree list has focus. Here is a demo of it. 

[psswdstore-tree-browser-demo.webm](https://user-images.githubusercontent.com/3914379/187090301-ce28d3c9-f64c-4791-949b-0c15840a1318.webm)

2022-09-09 15:12 UTC, patgmiller commented
> @patgmiller I'm midway through.

@erayd well it's been a month since you were "midway through", another week and we'll be two months into your review without any activity, I just curious on some sort of progress. 

If there were any corrections I could be making corrections while you're finishing your review.

2022-09-09 18:47 UTC, erayd commented
@patgmiller I apologise for the slow progress on my end of this; I am *very* aware that I've been holding you up in a big way. I'll try to get some sort of significant and useful direction to you by the end of the weekend. Hopefully that will be in the form of a finished code review, or if not then I'll post what I have so far. I've overall been pretty happy with what I've seen, so hopefully you won't have to put up with too much more of my holding things up on this one before it's merged.

I'm still flirting with burnout here, which makes this whole thing much harder to push through than would ordinarily be the case. The problem with reviewing a changeset this large on a security project is that I can't keep it all (along with all its context) sufficiently in my head between sessions, or pick it back up quickly with my head in that state. I can't spend too long with it at once without ending up staring at the screen getting nowhere (usually after I've followed something several layers deep to remember how all the parts interact), and every time I sit down with this I have to get back up to speed with it first to ensure I don't miss bits or make silly mistakes after spending the previous week or so buried in other problems.

Once this PR is merged, and the stuff comes in smaller bites (that can be reviewed in one go), progress on this project should hopefully be a lot faster. The biggest issue with reviewing this particular PR is simply the size of it / the amount of stuff it touches - I simply don't have the time (or energy) to do something this large all at once without being sloppy about it, and given the sensitivity of data we handle, I don't want to miss something important.

2022-09-10 01:27 UTC, patgmiller commented
@erayd I appreciate the clarification! I'm sorry for whatever items on your plate are contributing to your burnout and you're right, it wouldn't do at all to proceed in a sloppy manner given the security nature of the project. I'll make sure to keep that in mind, thanks so much.

2022-09-11 22:52 UTC, erayd commented
I am working on this now. Will post what I have as soon as I put it down.

2022-09-12 01:34 UTC, erayd requested changes
Thank you so much for your work on this, @patgmiller. Overall I'm really happy with what you've done here. Most of my nitpicks this time are just UI stuff, and the ones that aren't are still minor.

I reckon this is getting pretty close to merge-ready.

2022-09-12 01:34 UTC, erayd commented on src/popup/interface.js
>  const LATEST_NATIVE_APP_VERSION = 3000003;
Needs updating to match the version that contains these new capabilities.

2022-09-12 01:34 UTC, erayd commented on src/popup/interface.js
>      this.currentDomainOnly = !settings.tab.url.match(/^(chrome|about):/);
My understanding is that some chrome-based browsers put their own name in here. Is there a list of them somewhere that we can add here?

2022-09-12 01:34 UTC, erayd commented on src/popup/interface.js
> +                e.target.querySelector("div.action.details").click();
What is the purpose of this change?

2022-09-12 01:34 UTC, erayd commented on src/popup/layoutInterface.js
> + * compoenents.
Spelling (components) 😉

2022-09-12 01:34 UTC, erayd commented on src/popup/models/Login.js
> +        // a null content sha identifies this a new entry
Might be worth mentioning `isNew()` in this comment.

2022-09-12 01:34 UTC, erayd commented on src/popup/models/Login.js
> +    // ensure doAction works in detailInterface,
This looks like a todo.

2022-09-12 01:34 UTC, erayd commented on src/popup/models/Login.js
> + * @since 3.7.0
Wrong version.

2022-09-12 01:34 UTC, erayd commented on src/popup/models/Login.js
> +            const parts = secret.split(': ');
Should look explicitly for known prefixes here. Otherwise it'll exclude any secret that contains `:` followed by a space (which is admittedly an edge case, but IMO we should still handle it; I've run across a couple of these in the wild). There is an existing list of prefixes in the entry-parsing code - from memory I think this is just `password` and `secret`, but worth double-checking.

2022-09-12 01:34 UTC, erayd commented on src/popup/models/Login.js
> +        const request = JSON.parse(JSON.stringify(login));
I'm wondering if it might be worth breaking this out into a meaningfully-named helper function (something like `cloneToSerializable()`)? It's only one line of code, but we use it in a number of places, and as the reason is non-obvious, it needs the comment in every location too. With a function, we can give it a sane name, and put the comment there once in case anybody needs further detail about why it exists.

2022-09-12 01:34 UTC, erayd commented on src/popup/models/Settings.js
> +require("chrome-extension-async");
Not for this PR, but we may be able to get rid of this dependency with the MV3 change.

2022-09-12 01:34 UTC, erayd commented on src/popup/models/Tree.js
> +        // regex characters like [] or () and such
Why do they break it? IMO we should be handling these correctly, not aborting.

2022-09-12 02:23 UTC, erayd commented
One other thought - some of the theming colours on the new additions seem a bit off (albeit that colours can be quite subjective, so it's possible that it might be only me who feels this way). I don't want it to hold up this PR for it, but would be good if we can maybe nitpick these a bit at some point after it's merged.

2022-09-12 15:38 UTC, patgmiller commented
> Thank you so much for your work on this, @patgmiller. Overall I'm really happy with what you've done here. Most of my nitpicks this time are just UI stuff, and the ones that aren't are still minor.
> 
> I reckon this is getting pretty close to merge-ready.

Cool, I'll have a look this week. Thank you so much!

2022-09-16 01:00 UTC, patgmiller commented
> One other thought - some of the theming colours on the new additions seem a bit off (albeit that colours can be quite subjective, so it's possible that it might be only me who feels this way). I don't want it to hold up this PR for it, but would be good if we can maybe nitpick these a bit at some point after it's merged.

I'll be honest, with the newer elements (save,delete buttons, modal dialogue, and notifications, etc) I only got them to where I thought the might be good enough to merge. I am not at all stuck on them, feel free to tweak away.

2022-09-16 02:41 UTC, erayd commented
@patgmiller Sounds good. I'm happy for us to address any of the UI points I raised that aren't also a functional concern, after merging. We can nitpick over making it pretty later 🙂.

2022-09-16 02:51 UTC, patgmiller commented on src/popup/models/Tree.js
> +        // regex characters like [] or () and such
They break it because it `search` accepts regular expressions `regex` so when these and other special regex chars are used, it becomes an invalid regular expression. Some like those few examples mentioned `[` `]` `(` `)`, must be closed and would change the meaning of the search expression. But really, how many people do you know who escape and put these [reserved character sets](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Character_Classes) in the names of their directories and files?

As for handling them,

1. we can use the deprecated `escape` function - it might never be removed, but it's a risk and it doesn't help to match on those characters I tried it. It would allow the user to auto complete directories with those in them though, they would just have to type the words if they want it to filter correctly.
2. We could just to a `replace("[", "\[")` for example, but I think it should be limited to the same non alpha numeric characters we use in the password generation in order to keep it simple.  And in that case we should still keep the try catch because if we do miss one char, the worse case is the user has to finish typing the path instead. 

i'm in favor of option 2. I'll go ahead and do that for now.

2022-09-16 03:13 UTC, patgmiller commented on src/popup/models/Tree.js
> +        // regex characters like [] or () and such
fyi from [docs for](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/search) `String.prototype.search` 
> If regexp is not a RegExp object and does not have a Symbol.search method, it is implicitly converted to a [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) by using new RegExp(regexp).

2022-09-16 03:16 UTC, erayd commented on src/popup/models/Tree.js
> +        // regex characters like [] or () and such
I'm aware of a few. `()` in particular is commonly used to add supplementary information (e.g. `my file (v2)`).

I'm happy with approach 2. However, I'm unsure what relation it has to our password generation alphabet. Why not simply escape the list of chars that have special meaning in JS regex?

2022-09-16 03:44 UTC, patgmiller commented on src/popup/models/Tree.js
> +        // regex characters like [] or () and such
I meant what you said, I mean I didn't want to try and handle anything else but `\` and those specific ones. It's fixed and here's a video of it working. 

[escape-reserved-regular-expression-charsets.webm](https://user-images.githubusercontent.com/3914379/190552192-0eede287-dee2-4ba2-8d4d-edf5bfba2802.webm)

2022-09-16 03:46 UTC, patgmiller commented on src/popup/models/Settings.js
> +require("chrome-extension-async");
Yeah, I wondered about the MV3 warnings and how they might need to be addressed. Okay, got it. 👍🏻

2022-09-16 03:52 UTC, erayd commented on src/popup/models/Tree.js
> +        // regex characters like [] or () and such
Thanks for fixing it. Unsure why it's so verbose though? Why not simply use a one-liner like the following, rather than manually iterating through everything and creating tons of new strings?

```javascript
.search(searchTerm.replaceAll(/[!$()*+,-./:?\[\]^{|}.\\]/gui, c => `\\${c}`));

//or

searchTerm = searchTerm.replaceAll(/[!$()*+,-./:?\[\]^{|}.\\]/gui, c => `\\${c}`);
.search(searchTerm);
```

2022-09-16 03:54 UTC, patgmiller commented on src/popup/addEditInterface.js
> +        function pathKeyHandler(e) {
This is for the path field, there are no other key bindings on the details page and as I recall there weren't any there to begin with.

2022-09-16 03:57 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
When has the arrow up or down key ever been used as navigation in between form elements, if you did that how would you move up or down a line in a `textarea` without the mouse?

2022-09-16 03:58 UTC, erayd commented on src/popup/models/Settings.js
> +require("chrome-extension-async");
Yeah, updating to use MV3 (and all the annoying changes the go along with it) is probably our next big task. Needs to be done by January next year, because Google is removing support for publishing MV2 extensions then.

On the plus side, Browserpass doesn't make use of any of the really problematic parts of MV2 that don't translate well to MV3 (e.g. persistent background processes that actually need to be persistent), so it should mostly be fairly smooth. HTTP modal auth could give us a headache though.

2022-09-16 04:01 UTC, erayd commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
It's fairly common to do that, albeit not something Browserpass has had reason to do before this. More common in native applications than web stuff, but I raise it here for consistency, as we use arrow navigation on all the main popup elements, so to not do so on the details screen feels like a UX problem.

Other implementations I've seen generally have cursor move take precedence over navigating between elements.

2022-09-16 04:04 UTC, erayd commented on src/popup/addEditInterface.js
> +        function pathKeyHandler(e) {
My apologies - I meant to comment this where it applied to the details screen. The point is still valid, albeit this is the wrong place for me to have made it.

2022-09-16 04:06 UTC, erayd commented on src/popup/addEditInterface.js
> +        function pathKeyHandler(e) {
With that said, this may be a pre-existing oversight on my part, so feel free to ignore this one. I'm happy to make this issue my problem.

2022-09-18 20:46 UTC, patgmiller commented on src/popup/models/Tree.js
> +        // regex characters like [] or () and such
I initially tried a simpler approach like you suggest, however it quickly reminded me of the following xkcd comic, https://xkcd.com/1638 and after typing two characters exploded. 
![backslashes](https://user-images.githubusercontent.com/3914379/190927367-536a9f1b-48c7-4857-9803-26cb4a82ca4e.png)

I will take another look at it. But if if doesn't work out then perhaps we can table it in a ticket or just leave it as is.

2022-09-18 20:51 UTC, erayd commented on src/popup/models/Tree.js
> +        // regex characters like [] or () and such
If it helps - in JS regex, most special characters do not need escaping when they are present inside of a character class, even if they would normally need escaping elsewhere in the expression. Pretty much anything other than `[]\/` can simply be typed verbatim.

2022-09-18 21:19 UTC, patgmiller commented on src/popup/models/Tree.js
> +        // regex characters like [] or () and such
Makes sense. I tried following your suggestion with a slightly modified to fit with what I already had

```js
    const symbols = "[!$()*+,-./:?\[\]^{|}.\\]";
    let escapedSearch = searchTerm.replaceAll(`/${symbols}/gu`, c => `\\${c}`);
   // ...
    try {
        "".search(escapedSearch)
    } catch (error) {
        // still need to handle any errors we
        // might've missed; catch, log, and stop
        console.log(error);
        return results;
    }

    // no exact match, do fuzzy search
    parentNode.forEach((_, dir) => {
        if (dir.search(escapedSearch) > -1) {
            results.push(dir);
        }
    });
    return results;  
```

A search that includes any of these characters `( ) [ ]` still threw an error:

```
SyntaxError: Invalid regular expression: /[/: Unterminated character class (at popup.dist.js:50706:12)
    at String.search (<anonymous>)
    at searchTree (popup.dist.js:50706:12)
    at searchTree (popup.dist.js:50689:16)
    at searchTree (popup.dist.js:50689:16)
    at Tree.search (popup.dist.js:50674:12)
    at HTMLInputElement.setLogin (popup.dist.js:48931:43)
    at HTMLInputElement.<anonymous> (popup.dist.js:36130:13)
    at HTMLInputElement.callback (popup.dist.js:35818:23)
```

I wondered if I was loosing some of the required escaping in the js template so I gave `replaceAll` the exact regex `/.../gu` which seems to work fine. 

```js
    let escapedSearch = searchTerm.
        replaceAll(/[!$()*+,-./:?\[\]^{|}.\\]/gu, c => `\\${c}`);

    try {
        "".search(escapedSearch)
    } catch (error) {
        // still need to handle any errors we
        // might've missed; catch, log, and stop
        console.log(error);
        return results;
    }
```

2022-09-19 11:11 UTC, patgmiller commented on src/popup/addEditInterface.js
> +            symbols = false,
no particular reason, i think i set it that way b/c everything else was initially null / blank and it is easier to check if a string has them, than to assume they are present and then disable for a non-empty string. symbols are used in pass by default anyway so i'll set it to `true` by default.

2022-09-19 11:54 UTC, patgmiller commented on src/popup/addEditInterface.js
> +const symbolsRegEx = RegExp(/[^a-z0-9]+/, "i");
@erayd Regarding unicode characters and symbols, the password highlighting doesn't handle unicode either. 

```js
    return secret.split("").map((c) => {
        if (c.match(/[0-9]/)) {
            return m("span.char.num", c);
        } else if (c.match(/[^\w\s]/)) {
            return m("span.char.punct", c);
        }
        return m("span.char", c);
    });
```
The  middle condition block with `/[^\w\s]/` would also consider `ü` as a symbol. I think it would be easiest to just check if it contains any symbols from the set of characters we use for symbols generate a password. Like this 

```js
const containsSymbolsRegEx = RegExp(/[#$%&'()*+,./:;<=>?@^_`{|}~."\[\]\\-]/, "gi");

// ...
if (password.search(containsSymbolsRegEx) == -1) {
    this.setSymbols(false);
}
```

Should we also update the highlight method?

2022-09-19 22:10 UTC, erayd commented on src/popup/addEditInterface.js
> +const symbolsRegEx = RegExp(/[^a-z0-9]+/, "i");
> I think it would be easiest to just check if it contains any symbols from the set of characters we use for symbols...

The problem with that approach is that it will miss a lot of symbols; we only use a few of them in our generation alphabet. Suitable for the majority of cases, but there will be a bunch of edge stuff in common usage that it will miss.

Why not go with something like the following? `\p{L}` will match every single character that is considered a letter class. `\p{N}` and `\p{Z}` are the equivalent for numbers and whitespace respectively. As a negative match, this basically means: "if `password` contains anything that isn't a letter, number, or whitespace" - which seems like a pretty good rule to go with IMO.

```JS
this.setSymbols(!!(password.match(/[^\p{L}\p{N}\p{Z}]/u));
```

> Should we also update the highlight method?

I didn't think of that before, but yes - good idea.

2022-09-19 22:15 UTC, erayd commented on src/popup/addEditInterface.js
> +const symbolsRegEx = RegExp(/[^a-z0-9]+/, "i");
Actually, `/[\p{P}\p{S}]/u` might be a better option. That specifies punctuation & symbols explicitly, rather than by remainder.

2022-09-19 22:38 UTC, patgmiller commented on src/popup/addEditInterface.js
> +const symbolsRegEx = RegExp(/[^a-z0-9]+/, "i");
So what I don't want to do is to refactor the password generation to include unicode characters not in the list of symbols, that was something I mentioned awhile back. Additionally, what about website support for unicode in passwords. Those are what I was concerned about, it opens things up quite a bit more. I think it's a slightly bigger topic.

2022-09-19 22:43 UTC, erayd commented on src/popup/addEditInterface.js
> +const symbolsRegEx = RegExp(/[^a-z0-9]+/, "i");
> So what I don't want to do is to refactor the password generation to include unicode characters not in the list of symbols, that was something I mentioned awhile back.

I agree with you. For *generation*, we should be sticking with stuff in the ASCII range. I think the selection of symbols you have chosen for that is fine as-is.

> Additionally, what about website support for unicode in passwords.

If the user has an existing password with unicode in it, then the website clearly supports it. And if we aren't generating unicode passwords in Browserpass, then we will never cause an incompatibility issue.

> Those are what I was concerned about, it opens things up quite a bit more. I think it's a slightly bigger topic.

Can you clarify? I'm not seeing how it's a bigger topic... isn't this just about "which characters in this existing password are symbols"? And if there are symbols present, then we default symbol-mode for generation to on. It doesn't change anything about which symbols we generate with.

2022-09-20 03:00 UTC, patgmiller commented on src/popup/addEditInterface.js
> +const symbolsRegEx = RegExp(/[^a-z0-9]+/, "i");
If we're not changing the symbols we're generating for now, it's fine. What I meant by bigger, was if we were do consider generating passwords with unicode, then I would think we'd be considering multi-lingual character sets. That's what I was worried about not wanting to add to this PR :)

2022-09-20 03:05 UTC, erayd commented on src/popup/addEditInterface.js
> +const symbolsRegEx = RegExp(/[^a-z0-9]+/, "i");
Got it - I think we are on the same page then.

For what it's worth, I personally do not think we should *ever* generate passwords outside of the standard ASCII set. It's IMO too high a risk of running into incompatibility issues, for very marginal gain.

2022-09-21 02:39 UTC, patgmiller commented on src/popup/models/Login.js
> +            const parts = secret.split(': ');
This does look explicitly for prefixes. It does a search 
```js
let index = text.search(multiLineSecretRegEx);
```
which is defined at top of the file as 
```js
// Search for one of the secret prefixes
// from Array helpers.fieldsPrefix.secret
const
    multiLineSecretRegEx = RegExp(`^(${helpers.fieldsPrefix.secret.join("|")}): `, 'mi')
;
```
However, i did some tests and it does have an edge case which I'll push a fix for it.

2022-09-21 02:48 UTC, erayd commented on src/popup/models/Login.js
> +            const parts = secret.split(': ');
Thanks - apologies for misinterpreting that!

I did notice that your commit also removed `trim()`; is there a reason for that? Main concern would be trailing whitespace on the password line.

2022-09-21 04:16 UTC, patgmiller commented on src/popup/models/Login.js
> +        const request = JSON.parse(JSON.stringify(login));
@erayd sounds good. i started on this but found there is one already it is in `src/background.js` and was added by @maximbaz 

```shell
git blame src/background.js -L 602,604

64c95daa (Maxim Baz 2019-02-23 23:17:14 +0100 602) function deepCopy(obj) {
64c95daa (Maxim Baz 2019-02-23 23:17:14 +0100 603)     return JSON.parse(JSON.stringify(obj));
64c95daa (Maxim Baz 2019-02-23 23:17:14 +0100 604) }
```
So i was thinking we just move that one to helpers so it can be shared and add the comment to it

2022-09-21 04:25 UTC, erayd commented on src/popup/models/Login.js
> +        const request = JSON.parse(JSON.stringify(login));
Sounds good 🙂

2022-09-21 04:35 UTC, patgmiller commented on src/popup/models/Login.js
> +        const request = JSON.parse(JSON.stringify(login));
I pushed it in commit [6f67a5d](https://github.com/browserpass/browserpass-extension/pull/290/commits/6f67a5df435d54dfb4b7da624255f2b5a30d7146), but if you'd rather we change something about it let me know.

2022-09-21 04:38 UTC, erayd commented on src/popup/models/Login.js
> +        const request = JSON.parse(JSON.stringify(login));
Could maybe get rid of the comment on line 121 of helpers.js, but otherwise looks good. Thanks 🙂.

2022-09-21 15:55 UTC, patgmiller commented on src/popup/models/Login.js
> +        const request = JSON.parse(JSON.stringify(login));
Sure, nice catch. Thanks.

2022-09-21 15:59 UTC, patgmiller commented on src/popup/models/Login.js
> +            const parts = secret.split(': ');
Yes, so I realized while going back over it, that the 2nd `trim()` was redundant since line 238 will already have handled any leading and trailing whitespace.

2022-09-21 20:52 UTC, erayd commented on src/popup/models/Login.js
> +            const parts = secret.split(': ');
Makes sense - well spotted 👍

2022-09-23 01:02 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                                m.route.set("/list");
Why do you think that?

2022-09-23 01:05 UTC, patgmiller commented on src/popup/colors.less
> +            a {
I think I understand hover highlight, but for 
> Should occupy the full width of the container.
Are you saying list of directories should be as wide as the entire html body for the popup?

2022-09-23 01:06 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            // onclick: clearStoreDirsV2,
They were a failed implementation for on click handlers to hide the tree dirs. I'll remove them.

2022-09-23 01:13 UTC, erayd commented on src/popup/addEditInterface.js
> +                                m.route.set("/list");
Because a back-arrow button in a UI normally means "return to previous". In this case, the previous screen was viewing details of the password entry. Having it jump all the way back to the main list IMO violates the intuitive expectation for what such a control should do.

2022-09-23 01:15 UTC, erayd commented on src/popup/colors.less
> +            a {
Nope. I'm saying that the highlight should span the entire width of the directory list, rather than just highlighting the text (i.e. the entire line gets highlighted).

2022-09-23 13:37 UTC, patgmiller commented on src/popup/colors.less
> +            a {
I thought it was, turns out Chrome was including an `outline` style, which I'm guessing you weren't seeing; that's why I was confused. I pushed a change to highlight the whole line on hover and focus-visible.

2022-09-23 13:43 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                                m.route.set("/list");
Okay, I'll take a look. i'll have to see how either mithril or browser handles a previous page request, b/c the `details` page, is currently the first time a secret is decrypted, so doing another page request of the details would ask for decryption again.

2022-09-24 02:06 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                                m.route.set("/list");
okay, that's been updated to return to the details view from edit view

2022-09-24 02:13 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                this.setStorePath();
This is the `oninit` method, the only time the `storeId` is provided to the argument of the `setStorePath` is for a change event on the select element. I suppose I should update the description and provide a `null` for clarity. How was the store incorrectly displayed?

2022-09-24 02:17 UTC, erayd commented on src/popup/addEditInterface.js
> +                this.setStorePath();
> How was the store incorrectly displayed?

It displays the wrong store entirely. The store displayed is the first one in the list, rather than being the store to which the entry being edited belongs.

2022-09-24 02:32 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                this.setStorePath();
Just to be clear, this is when `editing` an existing secret and what browser are you using?

2022-09-24 02:40 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                this.setStorePath();
Never mind, i was able to duplicate it in chrome. I'll fix it.

2022-09-24 02:50 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                this.setStorePath();
So the text in the path to the right is updated, but the selected option is not, I think the select element is disabled before the update happens.  

![Screenshot_2022-09-23_20-49-33](https://user-images.githubusercontent.com/3914379/192076986-2a6e230d-b77e-43f3-91f6-5bfa2968f71b.png)

2022-09-24 03:08 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                this.setStorePath();
Nice catch, here's the working fix with it showing the correct store selected. I'll push it momentarily.

![Screenshot_2022-09-23_21-05-28](https://user-images.githubusercontent.com/3914379/192077459-08d08a38-ee93-439f-89de-dacea7b2db21.png)
![Screenshot_2022-09-23_21-06-03](https://user-images.githubusercontent.com/3914379/192077460-fa7da3af-da4f-49d7-9bf4-4d0b6a5d5597.png)
![Screenshot_2022-09-23_21-06-54](https://user-images.githubusercontent.com/3914379/192077461-4c05f7df-9c7b-402d-882e-37c274261950.png)

2022-09-24 21:31 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("div.options", [
I've removed the border around the options. However I intentionally increased the size the checkbox because it seemed too small. Is that what you're referring to?

2022-09-24 21:59 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                                "select",
Do you want the `select` element colored, just the `options` colored, or both of them colored store colors? The options colors will only show when the drop down is open.

![Screenshot_2022-09-24_15-54-10](https://user-images.githubusercontent.com/3914379/192119988-4cb3c0e7-001d-46ec-bf20-58841ec22f8d.png)

![Screenshot_2022-09-24_15-58-20](https://user-images.githubusercontent.com/3914379/192120057-96e2532f-2836-4665-820e-2cafead36dd4.png)

2022-09-30 00:59 UTC, patgmiller commented on src/popup/interface.js
>  const LATEST_NATIVE_APP_VERSION = 3000003;
Okay, that's done.

2022-09-30 01:45 UTC, patgmiller commented on src/popup/interface.js
>      this.currentDomainOnly = !settings.tab.url.match(/^(chrome|about):/);
There isn't a list. This [zdnet - all-the-chromium-based-browsers](https://www.zdnet.com/pictures/all-the-chromium-based-browsers/2/) article was the closest thing I found, and there appear to be quite a few. I checked the top few but I don't want to dig through every one. If you want adding these might be good, beyond that I would wait till someone actually requests it. 

```text
chrome://, chromium and chrome
edge://, https://windows.tips.net/T013857_Edge_Chromium_Setting_URLs.html
opera://, https://help.opera.com/en/latest/advanced/
vivaldi://, https://help.vivaldi.com/desktop/appearance-customization/settings/
brave://, https://community.brave.com/t/adding-shortcuts-to-brave/135380
```

2022-09-30 02:02 UTC, patgmiller commented on src/popup/models/Login.js
> +    // ensure doAction works in detailInterface,
@erayd it's a comment about the code below it. should i add something like "This ensures `doAction` works ..."?

```js
    // This ensure doAction works in detailInterface,
    // and any other view in which it is necessary.
    this.doAction = helpers.withLogin.bind({
        settings: settings, login: login
    });
```

2022-09-30 02:05 UTC, patgmiller commented on src/popup/interface.js
> +                e.target.querySelector("div.action.details").click();
That was the fix to get the get details working again. It was changed about 7 months ago to this

```js
                        m("div.action.details", {
                            tabindex: 0,
                            title: "Open Details | <Ctrl+O>",
                            oncreate: m.route.link,
                            onupdate: m.route.link,
                            href: `/details/${result.store.id}/${encodeURIComponent(result.login)}`,
                        }),
```

Triggering the click was the simplest fix. It's one of two ways to trigger the request event in mithril api. Also because the actual `getDetails` is handled by the `Login` prototype now.

2022-09-30 02:08 UTC, erayd commented on src/popup/addEditInterface.js
> +                            m("div.options", [
For the border, yes - that looks much better 😁.

For the inconsistent sizing - that's part of it. The font size for the length number is also an issue. I'm not sure that just making the checkbox larger is the right way to do it either.

With that said, I'm happy to nitpick over the way this looks after the merge, so feel free to ignore this if you'd like.

2022-09-30 02:09 UTC, erayd commented on src/popup/addEditInterface.js
> +                                "select",
Both, please 🙂.

2022-09-30 02:11 UTC, erayd commented on src/popup/interface.js
> +                e.target.querySelector("div.action.details").click();
OK, thanks 🙂.

2022-09-30 02:11 UTC, erayd commented on src/popup/models/Login.js
> +    // ensure doAction works in detailInterface,
Yes please.

2022-09-30 02:13 UTC, patgmiller commented on src/popup/models/Login.js
> +        // a null content sha identifies this a new entry
Sure

2022-09-30 02:17 UTC, patgmiller commented on src/popup/detailsInterface.js
> +                                    disabled: true, // disable edit here
I guess I figured it should reinforce that editing shouldn't be allowed here. I'll remove it.

2022-09-30 02:22 UTC, erayd commented on src/popup/detailsInterface.js
> +                                    disabled: true, // disable edit here
If you feel that a comment reinforcing that is useful, I'm quite happy for it to remain provided it's clarified. The meaning needs to be clear to anyone else who might handle this code at a later date. Your call whether to do that or remove; I'm happy either way.

2022-09-30 02:24 UTC, patgmiller commented on src/popup/detailsInterface.js
> +                                              Moment(new Date(login.recent.when)).fromNow(),
Sure, I've created an issue with a reference to this.

2022-09-30 02:24 UTC, patgmiller commented on src/popup/interface.js
>      this.currentDomainOnly = !settings.tab.url.match(/^(chrome|about):/);
No problem, will do.

2022-09-30 02:31 UTC, patgmiller commented on src/popup/models/Login.js
> +    // ensure doAction works in detailInterface,
Done

2022-09-30 02:37 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                                "select",
Okay, just an FYI, I couldn't get the `hover/focused` option to keep it's store colors due to it not being consistent across browsers or just not avail. Some suggest implementing one's own drop down + options, which shouldn't be do bad just in mirthil. I just didn't want to do that in this PR.

2022-09-30 02:42 UTC, erayd commented on src/popup/addEditInterface.js
> +                                "select",
OK. Could you please open an issue for it then? And we can pick it up later.

2022-09-30 03:19 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                                "select",
Yep, done https://github.com/browserpass/browserpass-extension/issues/305

2022-09-30 03:21 UTC, erayd commented on src/popup/addEditInterface.js
> +                                "select",
Thanks 👍

2022-09-30 03:22 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=checkbox]", {
Okay. At first I didn't agree, but I checked out another password manager and it's done the same in other places. So will do.

2022-10-01 02:41 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
@erayd i believe this is more what you were going for with the `.gpg` suffix and file name, correct?

![Screenshot_2022-09-30_20-40-29](https://user-images.githubusercontent.com/3914379/193379948-e0cb4935-d43d-4bce-8e8c-c0d58cd69e27.png)

2022-10-01 02:45 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
In case it's not obvious, the `.gpg` is a separate `div` from the actual text field input

2022-10-01 02:50 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
If a picture is worth a thousand words, a video is what 1,000,000 words?

[filepath-and-suffix-behavior.webm](https://user-images.githubusercontent.com/3914379/193380202-fc98b04b-7671-4bab-8e99-abc07687a258.webm)

2022-10-01 02:57 UTC, erayd commented on src/popup/addEditInterface.js
> +                            m("input[type=text]", {
Yes, that is precisely what I was after - thanks 😁.

2022-10-01 18:02 UTC, patgmiller commented
You bet, I'll clean it up and push the changes.

-- 
Patrick Miller
***@***.***
https://github.com/patgmiller
https://www.linkedin.com/in/patgmiller/


On Fri, Sep 30, 2022 at 8:57 PM Erayd ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/popup/addEditInterface.js
> <https://github.com/browserpass/browserpass-extension/pull/290#discussion_r985028539>
> :
>
> > +                                },
>
> +                                stores.map(function (store) {
>
> +                                    return m(
>
> +                                        "option",
>
> +                                        {
>
> +                                            value: store.id,
>
> +                                            selected: store.id == vnode.attrs.storeid,
>
> +                                        },
>
> +                                        store.name
>
> +                                    );
>
> +                                })
>
> +                            ),
>
> +                            m("div.storePath", storePath),
>
> +                        ]),
>
> +                        m("div.path", [
>
> +                            m("input[type=text]", {
>
>
> Yes, that is precisely what I was after - thanks 😁.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/browserpass/browserpass-extension/pull/290#discussion_r985028539>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA53VC2PGXXN4XKNX55RW2DWA6SA5ANCNFSM5TAR6B3Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-01 22:36 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=checkbox]", {
@erayd could you clarify, 

> If the 'generate' button has been clicked

You're only referring to during the current edit, not to persist "if generate has been clicked" between saves, right?

2022-10-01 22:41 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("div.options", [
Okay, I'm not sure how to address it, so I'm happy to let you take a swing at it, do you want me to create an issue for it?

2022-10-01 23:14 UTC, erayd commented on src/popup/addEditInterface.js
> +                            m("input[type=checkbox]", {
Correct.

2022-10-01 23:16 UTC, erayd commented on src/popup/addEditInterface.js
> +                            m("div.options", [
No need for a distinct issue for this one I think. It comes under the "UI nitpicking" heading, which we will be doing anyway.

2022-10-02 15:00 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=checkbox]", {
Okay, sounds good. Thanks

2022-10-04 02:42 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                            m("input[type=checkbox]", {
done

2022-10-04 11:51 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                    storeDirs = storeTree.search(path);
@erayd So the `native` host is excluding `.git`, but are there specific `.` prefix folders you're concerned about? Or perhaps are there some  common practices you've notice which I'm just not aware of? I'm just not in the habit of putting any of these in my password store.

2022-10-04 11:59 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
I'm struggling a little with this, since it seems out of the norm from my experience. Other than in a table of form elements like a spread sheet of cells or similar, I don't recall coming across many input forms which use arrow navigation, do you know of any examples?

2022-10-04 14:47 UTC, patgmiller commented on src/popup/interface.js
> +                  "div.part.add",
While we're adjusting keyboard navigation to include the `Add` button. I was thinking we would also do the following

- "Tab" cycle would include `Add` button. 
  - when on last login moves to `Add`
  - when on `Add` moves to `Search` form
  - w/ Shift do reverse 
- "End" would go to the `Add` button now
- "Home" on `Add` button would go to `Search` form
- And add new case for `<Ctrl+A>` which go to `Add` view

@erayd what do you think?

2022-10-04 21:23 UTC, erayd commented on src/popup/addEditInterface.js
> +                    storeDirs = storeTree.search(path);
_Anything_ with a `.` prefix is hidden by convention; it's the standard way to denote a hidden filesystem item on UNIX-like platforms. There aren't specific directories I'm concerned about, so much as maintaining user expectations.

As an example, I have a `.bin` folder in one of my password stores, inside of which lives a copy of `pass` plus a bunch of other credential management scripts to make my life simpler. I never want to see that folder, and it doesn't contain any credentials - the whole reason I named it with a `.` was to stop it showing up.

2022-10-04 21:32 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                    storeDirs = storeTree.search(path);
Okay, no problem.

2022-10-04 21:37 UTC, erayd commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
`nmtui` is an example (as are a ton of curses-based apps). The Windows control panel applets are full of it (typically for navigating between controls within a section). Mikrotik winbox. Windows Explorer. Microsoft Teams.

It's often quite inconsistently applied, but it's all over the place.

@maximbaz What's your take on this?

2022-10-04 21:44 UTC, erayd commented on src/popup/interface.js
> +                  "div.part.add",
I approve of all of the above. Should also be possible to reach `Add` via arrows (same as how reaching `search` works, just with `add` at the bottom instead of the top).

2022-10-04 21:51 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
That explains my confusion, I was only considering browser based application. The ones you listed are terminal and OS based applications.

2022-10-04 22:01 UTC, erayd commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
Yeah, that was why I mentioned "more common in native applications" in my earlier comment. I haven't seen it often on the web. The only site I can think of off the top of my head is Teams, which has arrow navigation in parts of both the native and browser versions. I have encountered it occasionally elsewhere on the web, but it's certainly rare in that environment.

I consider Browserpass to be part of a native app (the browser), rather than a webpage - even though it's technically *implemented* as a webpage - hence why adhering to UX expectations for native stuff IMO makes sense. I'm happy to be convinced otherwise though - perhaps my own biases re stuff I commonly interact with are skewing my viewpoint a little?

2022-10-04 22:55 UTC, maximbaz commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
I think generally I don't have a strong opinion on the arrow navigation, because personally I always use Tab / Shift-Tab. On the main screen I might have to use arrows left and right once I reach the desired entry, but that in my mind is very intuitive. Arrows Up and Down there for me personally are just a neat bonus 🙂  

Having said that, I have a stronger preference for generally being able to do everything with keyboard, where right now for example I can reach the "View credentials" page, but not further. But I would be more than happy to have a separate ticket to revisit keyboard navigation across the extension.

In this particular case, I also agree with @patgmiller that I would maybe find it not intuitive that arrows up and down could be used until you reach a multi-line textarea, after which you are stuck inside and have to anyway use Tab / Shift-Tab to get out (unless we implement something custom that will allow to sometimes escape textarea using arrows up and down?). But maybe I just lack experience / imagination - I'm _not against_ arrow navigation if it's intuitive! 😄

2022-10-04 23:01 UTC, erayd commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
If you guys are both on the same page, then I think let's not implement arrow navigation on this page. It seems odd to me not to, but I'm happy to go with the majority view, and we can always add it later if people complain that it is missing.

2022-10-04 23:06 UTC, erayd commented on src/popup/addEditInterface.js
> +                    break;
> I have a stronger preference for generally being able to do everything with keyboard, where right now for example I can reach the "View credentials" page, but not further.

This, I agree with. The user should not have to pick up a mouse to use this.

2022-10-04 23:07 UTC, erayd commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
> I have a stronger preference for generally being able to do everything with keyboard, where right now for example I can reach the "View credentials" page, but not further.

This, I agree with. The user should not have to pick up a mouse to use this.

2022-10-04 23:25 UTC, maximbaz commented
Hey guys, once again - super cool job, thanks for all the work here, and I am sorry I am giving this PR less attention than it definitely deserves!

I just have some additional generic feedback from a user perspective - we can always choose to exclude this from the scope of this PR if need be 👍 Sorry in advance if you already discussed those and I missed the thread...

0. First of all, it's a lot more polished right now, feels.... _complete_, and behaves in exactly the way I expect it to - really cool feeling! 🚀 
1. On the "Add credentials" page, it would be nice to remember the last selected values of password Symbols and Length - it feels intuitive that if I changed length to 20, unticked the Symbols checkbox and left the popup, next time I use "Add credentials" it would default to 20 and no symbols.
2. Also on the "Add credentials" page: when I click on the "filename", the dropdown appears with folders - I feel like they should all have a trailing `/` symbol, to indicate that this is indeed a folder - when we insert the value, we do insert the trailing slash after all.
3. The above dropdown can only be completed with Enter, I actually first tried to click on an entry with a mouse, and that did nothing, so I thought the dropdown is not implemented fully yet, until I decided to try Enter... Would it be difficult to also support click to select?
4. On the "Edit credentials", I somehow expect that the buttons "Save" and "Delete" should be swapped, can't really explain it, just a feeling that the "Good" action must be on the right side...? 😅  (also on "Add credentials").

2022-10-04 23:29 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
> Yeah, that was why I mentioned "more common in native applications" in my earlier comment.

I must've missed that part previously, probably trying to juggle too many things. So I'm not against arrows up/down. I can definitely see it in more native apps, and with browserpass being primarily local requests I see why you'd consider closer to native than web. Also, I fully support depending on the mouse as little as possible. @erayd Are you okay if we make that a separate ticket? Basically, the full keyboard shortcuts + UI navigation to add/edit view and whatever else we're missing?

2022-10-04 23:31 UTC, erayd commented on src/popup/addEditInterface.js
> +                case "ArrowUp":
> Are you okay if we make that a separate ticket? Basically, the full keyboard shortcuts + UI navigation to add/edit view and whatever else we're missing?

Yep, that's fine with me 🙂.

2022-10-04 23:34 UTC, erayd commented
> On the "Edit credentials", I somehow expect that the buttons "Save" and "Delete" should be swapped, can't really explain it, just a feeling that the "Good" action must be on the right side...? 😅 (also on "Add credentials").

For what it's worth, 1Password has them with save-right / delete-left as well.

<img width="592" alt="Screen Shot 2022-10-05 at 12 33 16" src="https://user-images.githubusercontent.com/121486/193949370-ed99a063-f08e-4d10-b170-2e315c2966b0.png">

2022-10-05 05:50 UTC, erayd commented
Just noticed that the editor seems to be sneaking an extra newline in there that isn't present in the original file - could that be removed please?
<img width="408" alt="Screen Shot 2022-10-05 at 18 46 08" src="https://user-images.githubusercontent.com/121486/193989972-8740ebb3-83b9-4fba-b248-1ba90c38ad6f.png">

It doesn't seem to save the extra newline, which is good - and if there are already trailing newlines, it respects them.

2022-10-05 14:59 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                    storeDirs = storeTree.search(path);
Fixed

2022-10-06 07:18 UTC, patgmiller commented
> Hey guys, once again - super cool job, thanks for all the work here, and I am sorry I am giving this PR less attention than it definitely deserves!
> 
> I just have some additional generic feedback from a user perspective - we can always choose to exclude this from the scope of this PR if need be +1 Sorry in advance if you already discussed those and I missed the thread...
- [ ] address @maximbaz [comments](https://github.com/browserpass/browserpass-extension/pull/290#issuecomment-1267713933)

2022-10-06 07:22 UTC, patgmiller commented
> > On the "Edit credentials", I somehow expect that the buttons "Save" and "Delete" should be swapped, can't really explain it, just a feeling that the "Good" action must be on the right side...? sweat_smile (also on "Add credentials").
> 
> For what it's worth, 1Password has them with save-right / delete-left as well.
> 
> <img alt="Screen Shot 2022-10-05 at 12 33 16" width="592" src="https://user-images.githubusercontent.com/121486/193949370-ed99a063-f08e-4d10-b170-2e315c2966b0.png">

Yep, no problem. Even the example in my original response has it as you described. No idea why I why I swapped it.

2022-10-06 08:17 UTC, patgmiller commented on src/popup/interface.js
> +                  "div.part.add",
@erayd I've updated the key handlers to include the `Add credentials`, would you have another look at that specifically. Thanks. 

> Should still be displayed when the native host is out of date, but when clicked should prompt the user to update their native host to at least version X.

I have not yet adjusted to account for this part.

2022-10-08 20:32 UTC, patgmiller commented on src/popup/interface.js
> +                  "div.part.add",
@erayd The add button is always displayed now and I've added a notification for the user to update the native-host when they click the add or request the add view, which is also redirected to the list page. 

However, I'd like your input. There is currently already a div block informing user that native-host needs to be updated, but it currently shows under that `add` button. Right now the additional notification is only shown if they click the add button. Should we keep or change anything about the existing div block in in red text? See attached.

![Screenshot_2022-10-08_14-21-33](https://user-images.githubusercontent.com/3914379/194726811-32213df1-a3f8-4cfe-94a6-03ef590754c6.png)

![Screenshot_2022-10-08_14-22-18](https://user-images.githubusercontent.com/3914379/194726814-7ad73e2b-74bc-4998-bec6-f88bb6d0a71f.png)

One more to show notification when list is small or filtered below.

![Screenshot_2022-10-08_14-24-51](https://user-images.githubusercontent.com/3914379/194726820-e7054f65-8125-4a43-a775-bb66769ecd1c.png)

2022-10-09 01:06 UTC, patgmiller commented on src/popup/addEditInterface.js
> +                    break;
@erayd Wish granted! My only question is should it completely stop the popup from existing on the `/list` page, or should we keep the default handling there?

[escape-keyhandling.webm](https://user-images.githubusercontent.com/3914379/194732798-b061df25-a2d8-408b-9a95-bbea51720626.webm)

2022-10-11 10:20 UTC, patgmiller commented
Hi @maximbaz I've addressed all but `#1` for which I need clarification before proceeding.

> Hey guys, once again - super cool job, thanks for all the work here, and I am sorry I am giving this PR less attention than it definitely deserves!
> 
> I just have some additional generic feedback from a user perspective - we can always choose to exclude this from the scope of this PR if need be +1 Sorry in advance if you already discussed those and I missed the thread...
> 
> 0. First of all, it's a lot more polished right now, feels.... _complete_, and behaves in exactly the way I expect it to - really cool feeling! rocket
Thanks!

> 1. On the "Add credentials" page, it would be nice to remember the last selected values of password Symbols and Length - it feels intuitive that if I changed length to 20, unticked the Symbols checkbox and left the popup, next time I use "Add credentials" it would default to 20 and no symbols.
Are you saying this should persist between open / close of the browserpass popup, or just for the current open session? I imagine it will be requested at some point to have persistent defaults which can be set.

> 2. Also on the "Add credentials" page: when I click on the "filename", the dropdown appears with folders - I feel like they should all have a trailing `/` symbol, to indicate that this is indeed a folder - when we insert the value, we do insert the trailing slash after all.
Done

> 3. The above dropdown can only be completed with Enter, I actually first tried to click on an entry with a mouse, and that did nothing, so I thought the dropdown is not implemented fully yet, until I decided to try Enter... Would it be difficult to also support click to select?
Was there originally, it's fixed now.

> 4. On the "Edit credentials", I somehow expect that the buttons "Save" and "Delete" should be swapped, can't really explain it, just a feeling that the "Good" action must be on the right side...? sweat_smile  (also on "Add credentials").
Updated

2022-10-11 10:29 UTC, patgmiller commented on src/popup/interface.js
> +                  "div.part.add",
@erayd I am waiting to hear your feedback on this.

2022-10-11 10:35 UTC, erayd commented on src/popup/interface.js
> +                  "div.part.add",
@patgmiller I'm mostly away from my desk this week - so expect most of my feedback on recent changes to come through next week.

I like what you've done with the new upgrade notification. It looks great in those screenshots 😁. As for the existing one, I think it should stay as-is. I think they coexist well, and each serves a different purposes.

If these notifications looks / behave as your screenshots show, then I don't think any further changes to them are needed.

2022-10-11 10:37 UTC, erayd commented on src/popup/interface.js
> +                  "div.part.add",
> I've updated the key handlers to include the Add credentials, would you have another look at that specifically. Thanks.

This bit, I'll look at next week.

2022-10-11 10:44 UTC, maximbaz commented
> Are you saying this should persist between open / close of the browserpass popup, or just for the current open session? I imagine it will be requested at some point to have persistent defaults which can be set.

I agree we should have it persist across sessions 👍

2022-10-11 10:51 UTC, patgmiller commented on src/popup/detailsInterface.js
> +                        Settings.prototype.canSave(settings)
@erayd this is done as you requested.

2022-10-11 10:54 UTC, erayd commented on src/popup/detailsInterface.js
> +                        Settings.prototype.canSave(settings)
Thanks 😁

2022-10-11 11:01 UTC, patgmiller commented
> > Are you saying this should persist between open / close of the browserpass popup, or just for the current open session? I imagine it will be requested at some point to have persistent defaults which can be set.
> 
> I agree we should have it persist across sessions +1

Initially, I was only asking for clarification and and figured it would eventually need to persist, but I wasn't saying I thought it should be done in this current PR. I'm fairly certain making it persist will require some adjustments to the extension settings, requests, and maybe some other things. I'd rather not try to do that now since I don't consider that a nit pick item. Can I add it as another task?

2022-10-11 11:06 UTC, patgmiller commented on src/popup/interface.js
> +                  "div.part.add",
@erayd sounds good, thanks.

2022-10-11 11:13 UTC, maximbaz commented
Certainly!

2022-10-11 11:28 UTC, patgmiller commented
> Certainly!

@maximbaz the issue for persisted / configured default options has been added, #307

2022-10-21 03:20 UTC, patgmiller commented
@erayd just a follow up, I believe I've addressed everything from your latest review.

2022-10-26 10:57 UTC, erayd commented
@patgmiller Thanks! I've got this PR calendared for Friday; will go through your changes then. If you've addressed them all, then I suspect this will be pretty much ready to merge as far as I'm concerned.

Have been running your branch as my daily driver for a while now, and overall I've been really happy with it.

2022-10-29 14:01 UTC, patgmiller commented
> > Just noticed that the editor seems to be sneaking an extra newline in there that isn't present in the original file - could that be removed please? <img alt="Screen Shot 2022-10-05 at 18 46 08" width="408" src="https://user-images.githubusercontent.com/121486/193989972-8740ebb3-83b9-4fba-b248-1ba90c38ad6f.png">
> > It doesn't seem to save the extra newline, which is good - and if there are already trailing newlines, it respects them.
> 
> @erayd this is fixed

@erayd Just an FYI, I had to revert [my "fix" for the sneaky new line](https://github.com/patgmiller/browserpass-extension/blob/edit-ui/src/popup/addEditInterface.js#L529) you mentioned b/c it was too aggressive. However, I don't recall that I actually ever saw it adding newlines. Could you attempt to reproduce it?

2022-10-29 14:44 UTC, patgmiller commented
@erayd I was able to reproduce the extra line thing, it only happens when the original already has ANY trailing white space, and it happens before the add / edit page, and even before the details page.

2022-11-04 05:41 UTC, patgmiller commented
@erayd @maximbaz on that extra line i am 99.999% certain it's a result of grabbing the text from stdout by the native host. The only true way to eliminate that correctly would be to `--decrypt` with `--output` to an actual file and read that. That runs the slight risk of leaving decrypted secrets lying around if not cleaning up correctly. 

I think it is much easier to remove the single last newline from end of the string. I've tested it out with varying sets of trailing white space in some secrets and I think it is solid. It does a one time removal of the last line in the Login object constructor. It will respect other trailing white space, such has having multiple lines at the end or a several spaces or tabs at end the last line of the file. @erayd would you have a look and let me know how it works on the one you noticed? thanks

2022-11-04 05:44 UTC, erayd commented
@patgmiller Not sure I quite understand - can you expand a bit on *how* you think this newline is being introduced? Simply taking using a stdout -> stdin pipeline does not inherently introduce them... what is the *actual* source?

2022-11-04 05:46 UTC, erayd commented
@patgmiller As I side note - I've not lost sight of the review, just held up with a very demanding blackbird fledgling. Should be back on track later next week once it's gone.

2022-11-04 07:41 UTC, patgmiller commented
> @patgmiller Not sure I quite understand - can you expand a bit on _how_ you think this newline is being introduced? Simply using a stdout -> stdin pipeline does not inherently introduce them... what is the _actual_ source?

First I checked every where in the extension and didn't find anywhere that adds space the end of the raw text. But it is there before getting to the Login constructor. 

We're not doing "Simply using a stdout -> stdin", it's a (file) stdin > gpg > stdout. After I couldn't find anything in the extension that might be introducing a new line, I considered it might be from the native host. So to answer your question as an example I just pushed a commit which copies the contents to an unused property `login.original` immediately after getting it from the native host. Since we can't do console log from `background.js`, later inside the Login constructor it will log the untouched string and the one with the trailing new line removed. Compare them to your own encrypted secret. 

I don't have an exact source, but I think it has to do with the shell and stdout. When the actual contents of a file or string written to stdout do not have an ending new line you get the percent character showing, however the stdout still includes a new line after that. 
![Screenshot_2022-11-04_01-34-31](https://user-images.githubusercontent.com/3914379/199918109-d56082eb-9a60-4e47-83d2-407e547252a6.png)

2022-11-04 07:57 UTC, erayd commented
> We're not doing "Simply using a stdout -> stdin", it's a (file) stdin > gpg > stdout.

Hang on - earlier, you said _"i am 99.999% certain it's a result of grabbing the text from stdout by the native host"_ - i.e. the stdout of gpg to the stdin of the native host. Is that not what you actually meant?

I'm really confused - where *precisely* do you think the newline is being introduced? I'm not disputing your conclusion, especially noting the high level of confidence you have indicated - but I would like to know where you think it is, so that we can fix it.

> So to answer your question as an example I just pushed a commit which copies the contents to an unused property login.original immediately after getting it from the native host.

That... doesn't answer the question. All it does is show that the newline is already present by the time we start processing the input from the native host. Which is useful in that it rules out a bunch of stuff, but it still doesn't tell me where the issue actually is, or why you think that it relates to the stdio pipeline in some way.

> Since we can't do console log from background.js...

You can do `console.log()` from background.js. Just use it exactly as normal. The output will show up in the dev tools console for the extension's background script.

> I don't have an exact source, but I think it has to do with the shell and stdout.

*Why* do you think this? Browserpass doesn't even use a shell at all, so I'm not sure how the shell could possibly have anything to do with it.

> When the actual contents of a file or string written to stdout do not have an ending new line you get the percent character showing, however the stdout still includes a new line after that.

Not sure what you're refering to re the `%` symbol - perhaps this is something your particular shell does? What is the `devpass` command in your screenshot - is it a modified native host binary?

2022-11-07 05:16 UTC, patgmiller commented
@erayd Sorry for the confusion, it was late for me when I sent that last message. I was right, and I was wrong, about the source of the problem, and you were right about it not being anything to do with stdout. 

1. It is not from stdout of gpg to the native host 
```shell
  ╭─◦ ~/playground/github.com/w3digitalfoundry/.password-store ‹master*› ‹kube: › ‹vendor: ›
  ╰─◦ OUT=$(gpg --decrypt --yes --quiet --batch browserpass/google.com/example-pass.gpg) 
  ╭─◦ ~/playground/github.com/w3digitalfoundry/.password-store ‹master*› ‹kube: › ‹vendor: ›
  ╰─◦ echo "'$OUT'" 
  'foobar bin bash
  password: ;6c$<>do6!-DH<3z=tDGN4/C|LfV%|rm

  email: example@example.com
  user: example

  edited: 2022-06-26'
```
2. I've already demonstrated / eliminated the browserpass-extension as a potential source for the extra newline. 
3. I believe it happens in the `helpers/helps.go func GpgDecryptFile` function, at the very last line.
   ```return stdout.String(), nil```

After some digging I confirmed it by wrapping the byte to string conversion with `strings.TrimSpace(stdout.String())` and then what I got back to the extension was exactly what gpg generated above. After some searching I found a comment on stackoverflow [about `strings.Split()`](https://stackoverflow.com/questions/5884154/read-text-file-into-string-array-and-write#:~:text=Note%20strings.Split,at%2020%3A33) and looking at the go source for the `String()` receiver for `bytes.Buffer`. I think the source of the extra new line is coming from the method of conversion of bytes to string in Golang. But I haven't proven it yet. I'll keep working on it this week.

2022-11-07 16:45 UTC, patgmiller commented
@erayd I have fixed the extra new line, however it requires the following branch of the native host app. https://github.com/patgmiller/browserpass-native/tree/implement-tree-save-delete

I would like @maximbaz 's input on it as well, for which I thought I had created a PR but it looks like I still have not. So I will do that soon.

2022-11-09 21:06 UTC, maximbaz commented
Guys, https://github.com/browserpass/browserpass-native/pull/129/commits/4e21346a8807447f7b519ffb94970f1c65bd24c3 seems like an enormous over-engineering for a problem that anyone would barely notice... Shall we consider perhaps unconditionally trim the trailing whitespaces in the login entry contents, and leave it at that? (for example, as per above snippet, using `strings.TrimSpace(stdout.String())`)

2022-11-09 21:20 UTC, erayd commented
I haven't had the time to look at it properly yet, but skimmed it and noticed it seems to be writing decrypted contents to disk. We should never, *ever* be doing that - it's totally unacceptable to be bypassing the user's storage encryption (especially without their consent!), and on many platforms will result in leaving plaintext secrets somewhere from which they are recoverable.

I will never be OK with ***any*** solution which saves plaintext to the filesystem.

> Shall we consider perhaps unconditionally trim the trailing whitespaces in the login entry contents, and leave it at that?

I would prefer that we actually fix the problem properly. Unconditional trim would be fine for read-only stuff, but given that we're going to be editing & saving content, I think it's important that we don't unliaterally introduce changes to it. Newline changes in particular (either appearing or disappearing) can mess with people's scripted workflows.

2022-11-09 21:37 UTC, maximbaz commented
You are completely right, I agree. OK I tried to reproduce now, to confirm that the issue is on Go side, but it seems just fine for me? @patgmiller could you try this experiment too?

![image](https://user-images.githubusercontent.com/1177900/200947039-c034495f-d82e-4f9a-9177-8e07624e509d.png)

<details>
<summary>Snippet for copy-paste</summary>

```sh
$ printf nonewline > nonewline

$ printf 'withnewline\n' > withnewline

$ cat nonewline
nonewline
$ cat withnewline
withnewline

$ gpg --encrypt -r 0xB5DB77409B11B601 nonewline

$ gpg --encrypt -r 0xB5DB77409B11B601 withnewline

$ c main.go
package main

import (
    "bytes"
    "fmt"
    "os"
    "os/exec"
)

func GpgDecryptFile(filePath string) string {
    passwordFile, err := os.Open(filePath)
    if err != nil {
        return ""
    }

    var stdout, stderr bytes.Buffer
    gpgOptions := []string{"--decrypt", "--yes", "--quiet", "--batch", "-"}

    cmd := exec.Command("gpg", gpgOptions...)
    cmd.Stdin = passwordFile
    cmd.Stdout = &stdout
    cmd.Stderr = &stderr

    if err := cmd.Run(); err != nil {
        return ""
    }

    return stdout.String()
}

func main() {
    fmt.Printf("-->%v<--\n", GpgDecryptFile("./nonewline.gpg"))
    fmt.Printf("-->%v<--\n", GpgDecryptFile("./withnewline.gpg"))
}

$ go run ./main.go
-->nonewline<--
-->withnewline
<--
```
</details>

2022-11-11 05:10 UTC, patgmiller commented
@maximbaz @erayd it wasn't happening at all with a trailing newline, it was happening when there was **extra white space at the end of the last line** which was not the new line character. It was just adding a newline.

That said, I can't duplicate it with the simplified commands, so there is still an element that the tests are missing. With this we've eliminated everything but Native Host interaction with back end code. I've attached an actual bash script which does what you provided (below), you'll have to rename it after downloading. Here's screen grab of my run. 
![Screenshot_2022-11-10_21-42-04](https://user-images.githubusercontent.com/3914379/201266018-e599e988-2e5c-4432-83ec-585dc21b26e2.png)

In the native host code changes, I've replaced the plain text file **test** approach i did previously, with a pipe output and pushed it to the native branch. It  

1. fixes the problem
2. doesn't modify any user content. either for code in host or extension
3. doesn't write plain text to storage
4. can hardly be called over engineering

[whitespace_test.sh.txt](https://github.com/browserpass/browserpass-extension/files/9986564/whitespace_test.sh.txt)

2022-11-18 16:02 UTC, maximbaz commented
>  it wasn't happening at all with a trailing newline, it was happening when there was extra white space at the end of the last line which was not the new line character. It was just adding a newline.

Right, sorry, you mentioned that before and it slipped my attention...

> That said, I can't duplicate it with the simplified commands

Yeah, I am trying your script and I can't replicate the issue with it either. To be honest, I can't replicate the issue even in the browser... With the latest code from this PR, and native host from [this PR](https://github.com/browserpass/browserpass-native/pull/99). Could I be doing something wrong? Or could it be something else at play here, like CRLF vs LF for example? Do you have an actual decrypted file which reproduces the problem? If so, could you zip it and attach, so I could try on it?

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/1177900/202747153-900bdc29-46ed-4adc-b550-6f3c8f049864.png)

![image](https://user-images.githubusercontent.com/1177900/202747020-73afa221-a73d-403c-9864-6a4da9f94cb7.png)

![image](https://user-images.githubusercontent.com/1177900/202747270-9da0dde6-681c-41a2-96d7-cd965eade303.png)

![image](https://user-images.githubusercontent.com/1177900/202747468-21844d70-c328-4727-8d34-3e70ddbf93a7.png)

</details>

2022-11-21 04:41 UTC, patgmiller commented
@maximbaz you could be right about there being something more at play, because I tried checking out the `helpers/helpers.go` version prior to my changes and it wasn't happening exactly as before. Give me a couple days to see if I can still reproduce it or not.

2022-11-26 06:55 UTC, patgmiller commented
@maximbaz I am able to replicate it now.

With the `browserpass-extension` at the latest for this PR. In your `browserpass-native` repo do the following: 

1. checkout the HEAD of my `implement-tree-save-delete` branch from my repo `git@github.com:patgmiller/browserpass-native.git`
2. then `git checkout a0672a21fabbca1751153aa7b9ee1929d66e1146 -- helpers/helpers.go` this was the first commit i added to your original changes in which I only changed the version. 
3. build native host and copy/move the `browserpass` binary correct location if different

In replicating the issue I am getting an extra new line `every` time, but you have to do `WITH` the `browserpass-native` and `broswerpass-extension`. As I mentioned originally I believe it is a combination of the native host app with the native messaging of the browser. 

Afterwards either do a hard reset, `git reset --hard`, or `git checkout -- helpers/helpers.go` , rebuild and re-test.

2022-12-17 14:17 UTC, maximbaz commented
I've just tried again, but weirdly I'm still not able to reproduce it 😐 

I hope I didn't misunderstand some of the repro steps, so let me try to very carefully document everything I did:

1. In `browserpass-native`, select the commit with the new version only `a0672a2`, confirm there are no local changes:

```sh
$ git status
HEAD detached at a0672a2
nothing to commit, working tree clean
```

2. Build using `make`, then move the binary to `/usr/bin/browserpass` (in my case it's the location).

3. In `browserpass-extension`, make sure I'm on the latest commit in your PR:

```sh
$ git status
On branch edit-ui
Your branch is up to date with 'patgmiller/edit-ui'.

nothing to commit, working tree clean

$ git rev-parse HEAD
997aaccc49f22b67c997408130237019dd809f5d
```

4. Then also `make` and refresh it in the Chromium browser in `chrome://extensions/`.

5. In the settings of Browserpass, select password store that contains the `nonewline.gpg` and `withnewline.gpg` that were created using your script above.

6. Now in Chromium, click on the popup, pick any of the two, and click the Edit button, and I'm expecting to see the extra newline, is that correct?

![image](https://user-images.githubusercontent.com/1177900/208246145-6f7485b6-c43b-4ac5-833d-c7566f661451.png)

![image](https://user-images.githubusercontent.com/1177900/208246181-4f54ce1b-24f9-4f40-9476-5a3f9df132ec.png)

Could it be a browser or OS combination, or specific password entry? Could you perhaps encrypt the test credentials file, on which you can reproduce the issue, with your and my PGP keys, so that we have an identical file, that we both can decrypt and use for testing? My public key is [here](https://maximbaz.com/pgp_keys.asc).

So to summarize, I've never been able to reproduce it so far in any conditions 😞  @erayd what about you, are you able to reproduce?

Is there anything else in this PR, that is pending before merge, besides this issue?

2022-12-21 03:52 UTC, patgmiller commented
@maximbaz if we're being exact there was one minor step omitted, which was to checkout just the `helpers/helpers.go` version of the that commit in the `browserpass-native` repo. 

```shell
git checkout a0672a21fabbca1751153aa7b9ee1929d66e1146 -- helpers/helpers.go
```

But for all intensive purposes your steps and test should've worked to reproduce the issue. So the only thing left I can think is perhaps it is a version of Chrome. However, my latest commit to the PR in `browserpass-native` fixes it. As far as I know the pseudo extra line was the only remaining issue to resolve.

For clarity I am on the following setup:

```
Google Chrome Version 108.0.5359.71 (Official Build) (64-bit)
```

```shell
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

```shell
uname -a
Linux friday 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

2022-12-21 04:21 UTC, patgmiller commented
@maximbaz for kicks here is a file i was able to reproduce the issue with 
[example-extra-lines.gpg.txt](https://github.com/browserpass/browserpass-extension/files/10274414/example-extra-lines.gpg.txt) drop the `.txt` ending and then decrypt 

To be clear, it has first line password and followed by two blank lines, shown below, for a total of 3 lines. But following my earlier test, will have 4 lines in the browser plugin.

Here is example content
```
iekideizaCee1xohjooGeir0


```

And here are non plugin output 

```shell
╭─◦ /tmp  ‹kube: › ‹vendor: ›
╰─◦ devpass browserpass/google.com/example-extra-lines 
iekideizaCee1xohjooGeir0


╭─◦ /tmp  ‹kube: › ‹vendor: ›
╰─◦ devpass browserpass/google.com/example-extra-lines | wc -l 
3
```

Also for clarity `devpass` is just an alias using `pass` 

```shell
╭─◦ /tmp  ‹kube: › ‹vendor: ›
╰─◦ which devpass
devpass () {
	PASSWORD_STORE_DIR=$HOME/path/to/the/dir/.password-store pass $@
}
```

I hope that helps, but it is not a problem in the latest version of the branch for the PR `browserpass-native`.

2022-12-22 01:11 UTC, erayd commented
> So to summarize, I've never been able to reproduce it so far in any conditions 😞 @erayd what about you, are you able to reproduce?

I could certainly reliably reproduce it before. I'm away from my usual computer until after New Year, but will take a look then and see if I can still reproduce it.

> Is there anything else in this PR, that is pending before merge, besides this issue?

I think it's just this. Will need a rebase on master though.

2022-12-22 20:01 UTC, maximbaz commented
Thank you for the file @patgmiller! I believe it helped me to finally understand what's going on, and I hope now to clarify it for you as well. Long post ahead, brace yourself 😁 

Everything starts with agreeing on a definition of a "line". 

[POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) defines a line as such: 

> A sequence of zero or more non-newline characters plus a terminating newline character.

`wc -l` counts therefore the number of newline characters (also known as `\n`, or `0a` in hex).

To demonstrate this, make sure to use `printf` and not `echo`, which gives precise control over every character to be printed.

```sh
$ printf 'first line' | wc -l
0
```

The output of `printf` produces an "invalid" line according to POSIX standard, a line that does not end with a newline character, therefore `wc -l` tells us that there are zero lines.

The snippet below is just to demonstrate that neither gpg nor pass are important here:

```sh
$ printf 'first line' > /tmp/entry
$ gpg --encrypt -r $id /tmp/entry
$ gpg --decrypt /tmp/entry.gpg | wc -l
0
$ PASSWORD_STORE_DIR=/tmp pass entry | wc -l
0
```

It really is just the number of newline characters that `wc -l` counts.

Now, if you explicitly add a newline character at the end, then you'd get the expected result of 1:

```sh
$ printf 'first line\n' | wc -l
1
```

Another way to see this is to explore file in hex, where `0a` would represent the "hidden" newline character:

```sh
$ printf 'first line' | od -A n -t x1z -v
 66 69 72 73 74 20 6c 69 6e 65                    >first line<

$ printf 'first line\n' | od -A n -t x1z -v
 66 69 72 73 74 20 6c 69 6e 65 0a                 >first line.<
```

Notice that we can clearly see the `0a` newline character in the end of the second output.

----

Now, let's take your `example-extra-lines.gpg.txt` file and analyze its contents with hex:

```sh
$ gpg --decrypt example-extra-lines.gpg 2>/dev/null | od -A n -t x1z -v
 69 65 6b 69 64 65 69 7a 61 43 65 65 31 78 6f 68  >iekideizaCee1xoh<
 6a 6f 6f 47 65 69 72 30 0a 0a 0a                 >jooGeir0...<
```

You can clearly see that the file ends with three newline characters, three `0a`.

Let's look at two `browserpass-native` hosts, first the version from my branch + version change (i.e. commit `a0672a2`):

![image](https://user-images.githubusercontent.com/1177900/209208911-288b865b-291a-493a-bc3a-6712b62f11bb.png)

As you can see, the file contents that the extension receives from native hosts correctly contains three `\n` newline characters, getting the entry contents exactly as it is stored on disk.

If we **view** the entry (not in the edit mode yet), by selecting everything, we see three lines of text (one line of text "iekideizaCee1xohjooGeir0" and two empty lines - probably what you also see in your own editor:

![image](https://user-images.githubusercontent.com/1177900/209212129-d1a60930-ccf4-4e3b-9885-98b3e10fc6bc.png)

It is in the edit mode, in the textarea, where cursor is seemingly on the fourth line:

![image](https://user-images.githubusercontent.com/1177900/209212451-53511af4-4fd0-4887-bd16-9a544091c135.png)

So it is an issue with Chromium, that it decides to represent each of the three newline characters on a new line.

However, if I don't change anything, press save, and inspect the contents of the file again, I will correctly see three newline characters - so the file contents correctly didn't change, and that's what's important.

```sh
$ gpg --decrypt example-extra-lines.gpg 2>/dev/null | od -A n -t x1z -v
 69 65 6b 69 64 65 69 7a 61 43 65 65 31 78 6f 68  >iekideizaCee1xoh<
 6a 6f 6f 47 65 69 72 30 0a 0a 0a                 >jooGeir0...<
```

Now, let's repeat the experiment with the latest commit from your branch in `browserpass-native` (i.e. `4c22ee04`).

If I explore the contents of the file, as received from native host, it would miss one newline character:

![image](https://user-images.githubusercontent.com/1177900/209214052-4cac4b52-e78c-4b87-af9c-576d53809368.png)

In the edit part of the extension, I will see only three lines, as we would expect:

![image](https://user-images.githubusercontent.com/1177900/209213881-d1190a93-5bde-4fa9-b963-1c6a5b6cc589.png)

However, if I don't change anything, click Save and explore the file contents, we observe that we incorrectly modified the file, and removed one line:

```sh
$ gpg --decrypt example-extra-lines.gpg 2>/dev/null | od -A n -t x1z -v
 69 65 6b 69 64 65 69 7a 61 43 65 65 31 78 6f 68  >iekideizaCee1xoh<
 6a 6f 6f 47 65 69 72 30 0a 0a                    >jooGeir0..<
```

Furthermore, if I repeat the action again (popup -> edit -> make no changes -> press Save -> explore file contents), I will see that the file is again modified:

```sh
$ gpg --decrypt example-extra-lines.gpg 2>/dev/null | od -A n -t x1z -v
 69 65 6b 69 64 65 69 7a 61 43 65 65 31 78 6f 68  >iekideizaCee1xoh<
 6a 6f 6f 47 65 69 72 30 0a                       >jooGeir0.<
```

And then again:

```sh
$ gpg --decrypt example-extra-lines.gpg 2>/dev/null | od -A n -t x1z -v
 69 65 6b 69 64 65 69 7a 61 43 65 65 31 78 6f 68  >iekideizaCee1xoh<
 6a 6f 6f 47 65 69 72 30                          >jooGeir0<
```

Until no more newline characters are left, and the file becomes stable. At this point, `wc -l` would (correctly) identify as the file containing zero lines.

```sh
$ gpg --decrypt example-extra-lines.gpg 2>/dev/null | wc -l
0
```

---

To summarize:

- I believe the changes in the `browserpass-native` should not be made, and we should return to commit `a0672a2`. 
- We can decide whether we want to do some magic to "fix" Chromium's representation of content in textarea on javascript side (e.g. by removing the last newline character before showing the edit form, and then adding it back before Save is pressed) or doing nothing. Because we don't know if all browsers of all versions are affected, as well as we probably won't be actively monitoring when Chromium gets this fixed, my personal vote is for not doing anything, but I don't have strong opinion here. 
- I care for us not changing file contents on disk if user made zero changes in the textarea, and I care for the native host to correctly send all characters of the file.

2022-12-22 21:09 UTC, patgmiller commented
@maximbaz technically `echo -n ""` would also not include the extra new line, but `printf` is more explicit so I'm good with either. thanks so much for your additional work on it. Personally I agree with your suggestions and I would also vote we do nothing.

2022-12-22 21:15 UTC, patgmiller commented
@maximbaz if the user hasn't made any changes, we can probably see that b/c a sha sum is generated for existing contents before presenting the edit and then just skip saving when no actual changes have been made.

2022-12-22 21:17 UTC, patgmiller commented
Pending @erayd comments, I will also revert additional changes to `browserpass-native` if that is the agreed decision.

2022-12-22 21:17 UTC, maximbaz commented
True, or you can just compare the strings directly, it would probably be an overkill to compute hashsum of what's likely just a few lines of text, instead of just comparing these texts directly. Good idea to do (maybe we can deactivate "Save" button if there are no changes made)

2022-12-22 23:27 UTC, erayd commented
Thank you very much @maximbaz for that detailed analysis, and @patgmiller for your work getting to the bottom of this also. I'm in agreement with you guys - now that it's understood, and it's confirmed it's not changing the file content, I'm happy for us to proceed.

> True, or you can just compare the strings directly, it would probably be an overkill to compute hashsum of what's likely just a few lines of text, instead of just comparing these texts directly. Good idea to do (maybe we can deactivate "Save" button if there are no changes made)

I agree with both of those points.

2023-03-01 00:40 UTC, erayd commented
@maximbaz Are we still waiting on anything for this one?

2023-03-03 19:37 UTC, maximbaz commented
I don't think so! I just tested once more in Firefox, everything seems to be great (found a small issue - deleting an entry seems to unnecessarily want to decrypt something - but we can take that separately). 

I give my approval :+1: Please go ahead and merge if you are also happy with it! 

I'll check the native host side of things, do a code review and merge if I'm happy with everything. 

Then maybe we can have a look at what else should go in the next release (at least, perhaps, updating all dependencies?), and coordinate to make a new release? What do you think?

2023-03-03 19:37 UTC, maximbaz approved these changes

2023-03-05 00:10 UTC, maximbaz commented
I went through the native host code, merged all pending items, fixed some low-hanging fruits from other open issues, updated dependencies, and cut a new release. On its own the new release neither does any harm as it's backwards-compatible, nor does it bring much benefits, but I imagine people will be quite eager to see this one merged and having a release of the extension soon :slightly_smiling_face:

2023-06-19 01:34 UTC, merged

2023-06-19 01:36 UTC, erayd commented
Thank you very, very much @patgmiller (and apologies for how long it's taken to get this merged). Your significant effort in implementing this is greatly appreciated!

2023-06-20 02:26 UTC, patgmiller commented
@erayd @maximbaz and all, you're welcome! it was tough at times, but hopefully the results are well worth it.